/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stoman.ui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.stoman.dao.DoiTacDAO;
import com.stoman.dao.LoaiDoiTacDAO;
import com.stoman.dao.PhieuDAO;
import com.stoman.entity.DoiTac;
import com.stoman.entity.LoaiDoiTac;
import com.stoman.utils.Auth;
import com.stoman.utils.MsgBox;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.validator.GenericValidator;

/**
 *
 * @author MinhNH
 */
public class DoiTacJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DoiTacJDialog
     */
    public DoiTacJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlBackground = new JPanel();
        pnlTblDoiTac = new JScrollPane();
        tblDoiTac = new JTable();
        pnlTimKiem = new JPanel();
        txtTimKiemDT = new com.stoman.utils.JTextFieldCustom(defaultSearchDoiTac);
        lblTimKiem2 = new JLabel();
        cboTimKiemDT = new JComboBox<>();
        lblTimKiemDT = new JLabel();
        pnlDieuHuongTitle = new JPanel();
        pnlDieuHuong = new JPanel();
        btnFirst = new JButton();
        btnPrev = new JButton();
        btnNext = new JButton();
        btnLast = new JButton();
        pnlLoaiDoiTac = new JPanel();
        pnlLstLoaiDoiTac = new JScrollPane();
        lstLDT = new JList<>();
        pnlChucNangLoaiDT = new JPanel();
        btnThemLDT = new JButton();
        btnXoaLDT = new JButton();
        btnSuaLDT = new JButton();
        txtTimKiemLDT = new com.stoman.utils.JTextFieldCustom(defaultSearchLoaiDT);
        lblTimKiemLDT = new JLabel();
        pnlThongTin = new JPanel();
        txtTenDT = new com.stoman.utils.JTextFieldCustom();
        txtDiaChi = new com.stoman.utils.JTextFieldCustom();
        txtEmail = new com.stoman.utils.JTextFieldCustom();
        txtDienThoai = new com.stoman.utils.JTextFieldCustom();
        rdoKhachHang = new JRadioButton();
        rdoNhaPhanPhoi = new JRadioButton();
        lblTenDT = new JLabel();
        lblDiaChi = new JLabel();
        lblEmail = new JLabel();
        lblDienThoai = new JLabel();
        lblVaiTro = new JLabel();
        pnlChucNangTitle = new JPanel();
        btnMoi = new JButton();
        btnThem = new JButton();
        btnXoa = new JButton();
        btnSua = new JButton();
        buttonGroup1 = new ButtonGroup();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StoMan - Qu\u1ea3n l\u00fd \u0111\u1ed1i t\u00e1c");
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                formWindowClosed(e);
            }
        });
        var contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());

        //======== pnlBackground ========
        {

            //======== pnlTblDoiTac ========
            {
                pnlTblDoiTac.setBorder(new TitledBorder(null, "Danh s\u00e1ch \u0111\u1ed1i t\u00e1c", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));
                pnlTblDoiTac.setOpaque(false);

                //---- tblDoiTac ----
                tblDoiTac.setFont(new Font("Segoe UI", Font.BOLD, 12));
                tblDoiTac.setModel(new DefaultTableModel(
                    new Object[][] {
                    },
                    new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ) {
                    Class<?>[] columnTypes = new Class<?>[] {
                        Integer.class, String.class, String.class, String.class
                    };
                    boolean[] columnEditable = new boolean[] {
                        false, false, false, false
                    };
                    @Override
                    public Class<?> getColumnClass(int columnIndex) {
                        return columnTypes[columnIndex];
                    }
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return columnEditable[columnIndex];
                    }
                });
                tblDoiTac.setOpaque(false);
                tblDoiTac.setRowHeight(25);
                tblDoiTac.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                tblDoiTac.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        tblDoiTacMouseClicked(e);
                    }
                });
                pnlTblDoiTac.setViewportView(tblDoiTac);
            }

            //======== pnlTimKiem ========
            {
                pnlTimKiem.setBorder(new TitledBorder(null, "T\u00ecm ki\u1ebfm", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));
                pnlTimKiem.setOpaque(false);

                //---- txtTimKiemDT ----
                txtTimKiemDT.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        txtTimKiemDTKeyReleased(e);
                    }
                });

                //---- lblTimKiem2 ----
                lblTimKiem2.setText("theo");

                //---- cboTimKiemDT ----
                cboTimKiemDT.setModel(new DefaultComboBoxModel<>(new String[] {

                }));
                cboTimKiemDT.addActionListener(e -> cboTimKiemDTActionPerformed(e));

                //---- lblTimKiemDT ----
                lblTimKiemDT.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                GroupLayout pnlTimKiemLayout = new GroupLayout(pnlTimKiem);
                pnlTimKiem.setLayout(pnlTimKiemLayout);
                pnlTimKiemLayout.setHorizontalGroup(
                    pnlTimKiemLayout.createParallelGroup()
                        .addGroup(pnlTimKiemLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblTimKiemDT)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTimKiemDT)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTimKiem2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboTimKiemDT, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                );
                pnlTimKiemLayout.setVerticalGroup(
                    pnlTimKiemLayout.createParallelGroup()
                        .addGroup(pnlTimKiemLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(pnlTimKiemLayout.createParallelGroup()
                                .addComponent(lblTimKiemDT)
                                .addGroup(pnlTimKiemLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTimKiemDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTimKiem2)
                                    .addComponent(cboTimKiemDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGap(9, 9, 9))
                );
            }

            //======== pnlDieuHuongTitle ========
            {
                pnlDieuHuongTitle.setBorder(new TitledBorder(null, "\u0110i\u1ec1u h\u01b0\u1edbng", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));
                pnlDieuHuongTitle.setOpaque(false);

                //======== pnlDieuHuong ========
                {
                    pnlDieuHuong.setLayout(new GridLayout());

                    //---- btnFirst ----
                    btnFirst.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/skip-to-start.png")));
                    btnFirst.setPreferredSize(new Dimension(30, 25));
                    btnFirst.addActionListener(e -> btnFirstActionPerformed(e));
                    pnlDieuHuong.add(btnFirst);

                    //---- btnPrev ----
                    btnPrev.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/double-left-24.png")));
                    btnPrev.setPreferredSize(new Dimension(30, 25));
                    btnPrev.addActionListener(e -> btnPrevActionPerformed(e));
                    pnlDieuHuong.add(btnPrev);

                    //---- btnNext ----
                    btnNext.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/double-right.png")));
                    btnNext.setPreferredSize(new Dimension(30, 25));
                    btnNext.addActionListener(e -> btnNextActionPerformed(e));
                    pnlDieuHuong.add(btnNext);

                    //---- btnLast ----
                    btnLast.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/skip-to-end.png")));
                    btnLast.setPreferredSize(new Dimension(30, 25));
                    btnLast.addActionListener(e -> btnLastActionPerformed(e));
                    pnlDieuHuong.add(btnLast);
                }

                GroupLayout pnlDieuHuongTitleLayout = new GroupLayout(pnlDieuHuongTitle);
                pnlDieuHuongTitle.setLayout(pnlDieuHuongTitleLayout);
                pnlDieuHuongTitleLayout.setHorizontalGroup(
                    pnlDieuHuongTitleLayout.createParallelGroup()
                        .addGroup(pnlDieuHuongTitleLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlDieuHuong, GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addContainerGap())
                );
                pnlDieuHuongTitleLayout.setVerticalGroup(
                    pnlDieuHuongTitleLayout.createParallelGroup()
                        .addGroup(pnlDieuHuongTitleLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(pnlDieuHuong, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                );
            }

            //======== pnlLoaiDoiTac ========
            {
                pnlLoaiDoiTac.setBackground(new Color(0x408494));
                pnlLoaiDoiTac.setBorder(new TitledBorder(null, "Lo\u1ea1i \u0111\u1ed1i t\u00e1c", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));
                pnlLoaiDoiTac.setOpaque(false);

                //======== pnlLstLoaiDoiTac ========
                {

                    //---- lstLDT ----
                    lstLDT.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            lstLDTMouseClicked(e);
                        }
                    });
                    pnlLstLoaiDoiTac.setViewportView(lstLDT);
                }

                //======== pnlChucNangLoaiDT ========
                {
                    pnlChucNangLoaiDT.setOpaque(false);
                    pnlChucNangLoaiDT.setLayout(new GridLayout(1, 3));

                    //---- btnThemLDT ----
                    btnThemLDT.setText("Th\u00eam");
                    btnThemLDT.addActionListener(e -> btnThemLDTActionPerformed(e));
                    pnlChucNangLoaiDT.add(btnThemLDT);

                    //---- btnXoaLDT ----
                    btnXoaLDT.setText("Xo\u00e1");
                    btnXoaLDT.addActionListener(e -> btnXoaLDTActionPerformed(e));
                    pnlChucNangLoaiDT.add(btnXoaLDT);

                    //---- btnSuaLDT ----
                    btnSuaLDT.setText("S\u1eeda");
                    btnSuaLDT.addActionListener(e -> btnSuaLDTActionPerformed(e));
                    pnlChucNangLoaiDT.add(btnSuaLDT);
                }

                //---- txtTimKiemLDT ----
                txtTimKiemLDT.addKeyListener(new KeyAdapter() {
                    @Override
                    public void keyReleased(KeyEvent e) {
                        txtTimKiemLDTKeyReleased(e);
                    }
                });

                //---- lblTimKiemLDT ----
                lblTimKiemLDT.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                GroupLayout pnlLoaiDoiTacLayout = new GroupLayout(pnlLoaiDoiTac);
                pnlLoaiDoiTac.setLayout(pnlLoaiDoiTacLayout);
                pnlLoaiDoiTacLayout.setHorizontalGroup(
                    pnlLoaiDoiTacLayout.createParallelGroup()
                        .addGroup(pnlLoaiDoiTacLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlLoaiDoiTacLayout.createParallelGroup()
                                .addGroup(pnlLoaiDoiTacLayout.createSequentialGroup()
                                    .addComponent(lblTimKiemLDT)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTimKiemLDT))
                                .addComponent(pnlChucNangLoaiDT, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlLstLoaiDoiTac, GroupLayout.Alignment.TRAILING))
                            .addContainerGap())
                );
                pnlLoaiDoiTacLayout.setVerticalGroup(
                    pnlLoaiDoiTacLayout.createParallelGroup()
                        .addGroup(pnlLoaiDoiTacLayout.createSequentialGroup()
                            .addGroup(pnlLoaiDoiTacLayout.createParallelGroup()
                                .addComponent(lblTimKiemLDT)
                                .addComponent(txtTimKiemLDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlLstLoaiDoiTac, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlChucNangLoaiDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                );
            }

            //======== pnlThongTin ========
            {
                pnlThongTin.setBorder(new TitledBorder(null, "Th\u00f4ng tin \u0111\u1ed1i t\u00e1c", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));

                //---- rdoKhachHang ----
                rdoKhachHang.setFont(new Font("Segoe UI", Font.BOLD, 12));
                rdoKhachHang.setForeground(new Color(0x13615b));
                rdoKhachHang.setSelected(true);
                rdoKhachHang.setText("Kh\u00e1ch h\u00e0ng");

                //---- rdoNhaPhanPhoi ----
                rdoNhaPhanPhoi.setFont(new Font("Segoe UI", Font.BOLD, 12));
                rdoNhaPhanPhoi.setForeground(new Color(0xa33422));
                rdoNhaPhanPhoi.setText("Nh\u00e0 ph\u00e2n ph\u1ed1i");

                //---- lblTenDT ----
                lblTenDT.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblTenDT.setForeground(new Color(0x666666));
                lblTenDT.setText("T\u00ean \u0111\u1ed1i t\u00e1c");

                //---- lblDiaChi ----
                lblDiaChi.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblDiaChi.setForeground(new Color(0x666666));
                lblDiaChi.setText("\u0110\u1ecba ch\u1ec9");

                //---- lblEmail ----
                lblEmail.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblEmail.setForeground(new Color(0x666666));
                lblEmail.setText("Email");

                //---- lblDienThoai ----
                lblDienThoai.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblDienThoai.setForeground(new Color(0x666666));
                lblDienThoai.setText("S\u1ed1 \u0111i\u1ec7n tho\u1ea1i");

                //---- lblVaiTro ----
                lblVaiTro.setFont(new Font("Segoe UI", Font.BOLD, 13));
                lblVaiTro.setForeground(new Color(0x666666));
                lblVaiTro.setText("Vai tr\u00f2");

                GroupLayout pnlThongTinLayout = new GroupLayout(pnlThongTin);
                pnlThongTin.setLayout(pnlThongTinLayout);
                pnlThongTinLayout.setHorizontalGroup(
                    pnlThongTinLayout.createParallelGroup()
                        .addGroup(pnlThongTinLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlThongTinLayout.createParallelGroup()
                                .addComponent(lblEmail)
                                .addComponent(lblDiaChi)
                                .addComponent(lblVaiTro)
                                .addComponent(lblTenDT)
                                .addComponent(lblDienThoai))
                            .addGap(10, 10, 10)
                            .addGroup(pnlThongTinLayout.createParallelGroup()
                                .addGroup(pnlThongTinLayout.createSequentialGroup()
                                    .addComponent(rdoKhachHang)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdoNhaPhanPhoi)
                                    .addGap(0, 163, Short.MAX_VALUE))
                                .addComponent(txtDiaChi, GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEmail, GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDienThoai)
                                .addComponent(txtTenDT))
                            .addContainerGap())
                );
                pnlThongTinLayout.setVerticalGroup(
                    pnlThongTinLayout.createParallelGroup()
                        .addGroup(pnlThongTinLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTenDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTenDT))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDiaChi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDiaChi))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmail))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDienThoai, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDienThoai))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoKhachHang)
                                .addComponent(lblVaiTro)
                                .addComponent(rdoNhaPhanPhoi))
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
            }

            //======== pnlChucNangTitle ========
            {
                pnlChucNangTitle.setBackground(Color.white);
                pnlChucNangTitle.setBorder(new TitledBorder(null, "Ch\u1ee9c n\u0103ng", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                    new Font("Segoe UI", Font.BOLD, 13)));
                pnlChucNangTitle.setOpaque(false);
                pnlChucNangTitle.setLayout(new GridBagLayout());

                //---- btnMoi ----
                btnMoi.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_document_24px.png")));
                btnMoi.setText("L\u00e0m m\u1edbi");
                btnMoi.setPreferredSize(new Dimension(140, 30));
                btnMoi.addActionListener(e -> btnMoiActionPerformed(e));
                pnlChucNangTitle.add(btnMoi, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
                    GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                    new Insets(0, 5, 0, 5), 0, 4));

                //---- btnThem ----
                btnThem.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_add_list_24px_4.png")));
                btnThem.setText("Th\u00eam \u0111\u1ed1i t\u00e1c");
                btnThem.setPreferredSize(new Dimension(140, 30));
                btnThem.addActionListener(e -> btnThemActionPerformed(e));
                pnlChucNangTitle.add(btnThem, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
                    GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                    new Insets(0, 5, 0, 5), 0, 4));

                //---- btnXoa ----
                btnXoa.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_delete_document_24px.png")));
                btnXoa.setText("Xo\u00e1 \u0111\u1ed1i t\u00e1c");
                btnXoa.setPreferredSize(new Dimension(140, 30));
                btnXoa.addActionListener(e -> btnXoaActionPerformed(e));
                pnlChucNangTitle.add(btnXoa, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
                    GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                    new Insets(0, 5, 0, 5), 0, 4));

                //---- btnSua ----
                btnSua.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/edit-property.png")));
                btnSua.setText("S\u1eeda \u0111\u1ed1i t\u00e1c");
                btnSua.setPreferredSize(new Dimension(140, 30));
                btnSua.addActionListener(e -> btnSuaActionPerformed(e));
                pnlChucNangTitle.add(btnSua, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
                    GridBagConstraints.NORTHWEST, GridBagConstraints.NONE,
                    new Insets(0, 5, 0, 5), 0, 4));
            }

            GroupLayout pnlBackgroundLayout = new GroupLayout(pnlBackground);
            pnlBackground.setLayout(pnlBackgroundLayout);
            pnlBackgroundLayout.setHorizontalGroup(
                pnlBackgroundLayout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlTblDoiTac)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(pnlTimKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlDieuHuongTitle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(pnlLoaiDoiTac, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlThongTin, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlChucNangTitle, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
            );
            pnlBackgroundLayout.setVerticalGroup(
                pnlBackgroundLayout.createParallelGroup()
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlLoaiDoiTac, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlThongTin, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlChucNangTitle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBackgroundLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlTimKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDieuHuongTitle, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlTblDoiTac, GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addContainerGap())
            );
        }
        contentPane.add(pnlBackground, BorderLayout.CENTER);
        pack();
        setLocationRelativeTo(getOwner());

        //---- buttonGroup1 ----
        buttonGroup1.add(rdoKhachHang);
        buttonGroup1.add(rdoNhaPhanPhoi);
    }// </editor-fold>//GEN-END:initComponents

    private void lstLDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLDTMouseClicked
        // TODO add your handling code here:
        if (lstLDT.isSelectionEmpty()) {
            return;
        }
        cboTimKiemDT.setSelectedIndex(0);
        this.fillToTableDoiTac();
        this.clearForm();
    }//GEN-LAST:event_lstLDTMouseClicked

    private void btnThemLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLDTActionPerformed
        // TODO add your handling code here:
        insertLDT();
    }//GEN-LAST:event_btnThemLDTActionPerformed

    private void btnXoaLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLDTActionPerformed
        // TODO add your handling code here:
        deleteLDT();
    }//GEN-LAST:event_btnXoaLDTActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblDoiTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoiTacMouseClicked
        // TODO add your handling code here:
        row = tblDoiTac.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblDoiTacMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void cboTimKiemDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimKiemDTActionPerformed
        // TODO add your handling code here:
        if (!lstLDT.isSelectionEmpty()) {
            txtTimKiemDT.setText(defaultSearchDoiTac);
            fillToTableDoiTac();
            clearForm();
        }
    }//GEN-LAST:event_cboTimKiemDTActionPerformed

    private void txtTimKiemDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemDTKeyReleased
        // TODO add your handling code here:
        if (lstLDT.isSelectionEmpty()) {
            return;
        }
        fillToTableDoiTac();
        clearForm();
    }//GEN-LAST:event_txtTimKiemDTKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.timer.stop();
    }//GEN-LAST:event_formWindowClosed

    private void btnSuaLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLDTActionPerformed
        // TODO add your handling code here:
        updateLDT();
    }//GEN-LAST:event_btnSuaLDTActionPerformed

    private void txtTimKiemLDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemLDTKeyReleased
        // TODO add your handling code here:
        modelDoiTac.setRowCount(0);
        fillToListLoaiDoiTac();
    }//GEN-LAST:event_txtTimKiemLDTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiTacJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiTacJDialog dialog = new DoiTacJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel pnlBackground;
    private JScrollPane pnlTblDoiTac;
    private JTable tblDoiTac;
    private JPanel pnlTimKiem;
    private JTextField txtTimKiemDT;
    private JLabel lblTimKiem2;
    private JComboBox<String> cboTimKiemDT;
    private JLabel lblTimKiemDT;
    private JPanel pnlDieuHuongTitle;
    private JPanel pnlDieuHuong;
    private JButton btnFirst;
    private JButton btnPrev;
    private JButton btnNext;
    private JButton btnLast;
    private JPanel pnlLoaiDoiTac;
    private JScrollPane pnlLstLoaiDoiTac;
    private JList<LoaiDoiTac> lstLDT;
    private JPanel pnlChucNangLoaiDT;
    private JButton btnThemLDT;
    private JButton btnXoaLDT;
    private JButton btnSuaLDT;
    private JTextField txtTimKiemLDT;
    private JLabel lblTimKiemLDT;
    private JPanel pnlThongTin;
    private JTextField txtTenDT;
    private JTextField txtDiaChi;
    private JTextField txtEmail;
    private JTextField txtDienThoai;
    private JRadioButton rdoKhachHang;
    private JRadioButton rdoNhaPhanPhoi;
    private JLabel lblTenDT;
    private JLabel lblDiaChi;
    private JLabel lblEmail;
    private JLabel lblDienThoai;
    private JLabel lblVaiTro;
    private JPanel pnlChucNangTitle;
    private JButton btnMoi;
    private JButton btnThem;
    private JButton btnXoa;
    private JButton btnSua;
    private ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables

    private DoiTacDAO dtDAO = new DoiTacDAO();
    private PhieuDAO pDAO = new PhieuDAO();
    private LoaiDoiTacDAO ldtDAO = new LoaiDoiTacDAO();
    private DefaultTableModel modelDoiTac;

    private int row = -1;

    private String defaultSearchLoaiDT = "Nhập từ khoá tìm kiếm loại đối tác";
    private String defaultSearchDoiTac = "Nhập từ khoá tìm kiếm đối tác";

    private void init() {
        setLocationRelativeTo(null);
        
        this.formatTable();

        this.fillToComboBoxTimKiemDT();
        this.fillToListLoaiDoiTac();
        this.updateStatus();

        timer.start();
    }

    // Đổ dữ liệu loại đối tác vào List
    private void fillToListLoaiDoiTac() {
        DefaultListModel lstModel = new DefaultListModel();
        String keyword = txtTimKiemLDT.getText();
        if (keyword.equals(defaultSearchLoaiDT)) {
            keyword = "";
        }
        try {
            List<LoaiDoiTac> list = ldtDAO.selectByKeyword(keyword);
            for (LoaiDoiTac ldt : list) {
                lstModel.addElement(ldt);
            }
            lstLDT.setModel(lstModel);
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    // Đổ dữ liệu vào bảng
    private SwingWorker worker;

    private void fillToTableDoiTac() {
        if (worker != null) {
            worker.cancel(true);
        }

        modelDoiTac.setRowCount(0);

        int maLDT = lstLDT.getSelectedValue().getMaLDT();
        int headerIndex = cboTimKiemDT.getSelectedIndex();

        try {
            worker = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    Thread.sleep(100);
                    String keyword = txtTimKiemDT.getText();
                    if (keyword.equals(defaultSearchDoiTac)) {
                        keyword = "";
                    }

                    List<DoiTac> list = null;
                    if (keyword.isEmpty()) {
                        list = dtDAO.selectByLoaiDT(maLDT);
                    } else {
                        list = dtDAO.selectByKeyword(maLDT, keyword, headerIndex);
                    }

                    int i = 1;
                    for (DoiTac dt : list) {
                        if (worker.isCancelled()) {
                            break;
                        }
                        modelDoiTac.addRow(new Object[]{
                            i++,
                            dt.getMaDT(),
                            dt.getTenDT(),
                            dt.getDiaChi(),
                            dt.getEmail(),
                            dt.getSoDT(),
                            dt.isVaiTro() ? "Nhà phân phối" : "Khách hàng"
                        });
                    }
                    if (worker.isCancelled()) {
                        modelDoiTac.setRowCount(0);
                    }
                    return null;
                }

                @Override
                protected void done() {
                    if (row >= 0) {
                        tblDoiTac.setRowSelectionInterval(row, row);
                    }
                }

            };
            worker.execute();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    // Đổ tên bảng vào ComboBox tìm kiếm
    private void fillToComboBoxTimKiemDT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTimKiemDT.getModel();
        model.removeAllElements();
        for (int i = 0; i < tblDoiTac.getColumnCount(); i++) {
            String columnName = tblDoiTac.getColumnName(i);
            if (columnName.equalsIgnoreCase("STT")) {
                continue;
            }
            model.addElement(columnName);
        }
    }

    // Lấy dữ liệu từ form
    private DoiTac getForm() {
        DoiTac dt = new DoiTac();
        dt.setTenDT(txtTenDT.getText().trim());
        dt.setMaDT(Integer.parseInt(txtTenDT.getToolTipText()));
        dt.setDiaChi(txtDiaChi.getText());
        dt.setEmail(txtEmail.getText());
        dt.setSoDT(txtDienThoai.getText());
        dt.setVaiTro(rdoNhaPhanPhoi.isSelected());
        dt.setMaLDT(lstLDT.getSelectedValue().getMaLDT());
        return dt;
    }

    // Nạp dữ liệu vào form
    private void setForm(DoiTac dt) {
        txtTenDT.setText(dt.getTenDT());
        txtTenDT.setToolTipText(String.valueOf(dt.getMaDT()));
        txtDiaChi.setText(dt.getDiaChi());
        txtEmail.setText(dt.getEmail());
        txtDienThoai.setText(dt.getSoDT());
        if (dt.isVaiTro()) {
            rdoNhaPhanPhoi.setSelected(true);
        } else {
            rdoKhachHang.setSelected(true);
        }
    }

    // Xoá trắng form
    private void clearForm() {
        setForm(new DoiTac());
        this.row = -1;
        tblDoiTac.clearSelection();
        this.updateStatus();
    }

    // Cập nhập trạng thái nút và bảng
    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblDoiTac.getRowCount() - 1);
        boolean isSelectedList = !lstLDT.isSelectionEmpty();

        btnXoa.setVisible(Auth.isManager());
        
        btnSuaLDT.setEnabled(isSelectedList);
        btnXoaLDT.setEnabled(isSelectedList);
        txtDiaChi.setEnabled(isSelectedList);
        txtDienThoai.setEnabled(isSelectedList);
        txtEmail.setEnabled(isSelectedList);
        txtTenDT.setEnabled(isSelectedList);

        btnThem.setEnabled(!edit && isSelectedList);
        btnSua.setEnabled(edit && isSelectedList);
        btnXoa.setEnabled(edit && isSelectedList);
        btnMoi.setEnabled(isSelectedList);

        btnFirst.setEnabled(!first && isSelectedList);
        btnPrev.setEnabled(!first && isSelectedList);
        btnNext.setEnabled(!last && isSelectedList);
        btnLast.setEnabled(!last && isSelectedList);
    }

    // Hiển thị đối tác được chọn từ bảng lên form
    private void edit() {
        int maDT = (int) tblDoiTac.getModel().getValueAt(tblDoiTac.convertRowIndexToModel(row), 1);
        DoiTac dt = dtDAO.selectByID(maDT);
        this.setForm(dt);
        this.updateStatus();
    }

    // Hiển thị đối tác đầu danh sách trên bảng
    private void first() {
        this.row = 0;
        this.edit();
        tblDoiTac.setRowSelectionInterval(row, row);
    }

    // Hiển thị đối tác kế trước
    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
            tblDoiTac.setRowSelectionInterval(row, row);
        }
    }

    // Hiển thị đối tác kế tiếp
    private void next() {
        if (this.row < (tblDoiTac.getRowCount() - 1)) {
            this.row++;
            this.edit();
            tblDoiTac.setRowSelectionInterval(row, row);
        }
    }

    // Hiển thị đối tác cuối danh sách trên bảng
    private void last() {
        this.row = tblDoiTac.getRowCount() - 1;
        this.edit();
        tblDoiTac.setRowSelectionInterval(row, row);
    }

    // Xác thực dữ liệu hợp lệ trên form
    private boolean isValidated() {
        String tenDT = txtTenDT.getText();
        String diaChi = txtDiaChi.getText();
        String email = txtEmail.getText();
        String dienThoai = txtDienThoai.getText();
        if (tenDT.isEmpty()) {
            MsgBox.alert(this, "Chưa nhập tên đối tác!");
            txtTenDT.requestFocus();
            return false;
        }
        if (diaChi.isEmpty()) {
            MsgBox.alert(this, "Chưa nhập địa chỉ!");
            txtDiaChi.requestFocus();
            return false;
        }
        if (email.isEmpty()) {
            MsgBox.alert(this, "Chưa nhập email!");
            txtEmail.requestFocus();
            return false;
        }
        if (!GenericValidator.isEmail(email)) {
            MsgBox.alert(this, "Email không hợp lệ!");
            txtEmail.requestFocus();
            return false;
        }
        if (dienThoai.isEmpty()) {
            MsgBox.alert(this, "Chưa nhập số điện thoại");
            txtDienThoai.requestFocus();
            return false;
        }
        if (!dienThoai.matches("((84)|(0))\\d{9}")) {
            MsgBox.alert(this, "Số điện thoại không hợp lệ!");
            txtDienThoai.requestFocus();
            return false;
        }
        return true;

    }

    // Thêm loại đối tác vào danh sách
    private void insertLDT() {
        String tenLDT = MsgBox.prompt(this, "Tên loại đối tác mới:");
        if (tenLDT != null && !tenLDT.isEmpty()) {
            LoaiDoiTac loaiDT = new LoaiDoiTac(tenLDT);
            try {
                ldtDAO.insert(loaiDT);
                this.fillToListLoaiDoiTac();
                this.clearForm();
                modelDoiTac.setRowCount(0);
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại!");
                e.printStackTrace();
            }
        }
    }

    // Thêm loại đối tác vào danh sách
    private void updateLDT() {
        LoaiDoiTac ldt = lstLDT.getSelectedValue();
        String tenLDT = MsgBox.prompt(this, "Tên loại đối tác mới:", ldt.getTenLDT());
        if (tenLDT != null && !tenLDT.isEmpty()) {
            ldt.setTenLDT(tenLDT);
            try {
                ldtDAO.update(ldt);
                this.fillToListLoaiDoiTac();
                MsgBox.alert(this, "Đổi tên thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Đổi tên thất bại!");
                e.printStackTrace();
            }
        }
    }

    // Xoá loại đối tác khỏi danh sách
    private void deleteLDT() {
        String message = "Các đối tác thuộc loại đối tác này sẽ bị xoá!"
                + "\nBạn có muốn tiếp tục xoá không?";
        if (MsgBox.confirm(this, message)) {
            LoaiDoiTac ldt = lstLDT.getSelectedValue();
            try {
                ldtDAO.delete(ldt.getMaLDT());
                this.fillToListLoaiDoiTac();
                this.clearForm();
                modelDoiTac.setRowCount(0);
                MsgBox.alert(this, "Xoá thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoá thất bại!");
                e.printStackTrace();
            }
        }
    }

    // Thêm đối tác vào CSDL
    private void insert() {
        if (isValidated()) {
            DoiTac dt = getForm();
            try {
                dtDAO.insert(dt);
                this.fillToTableDoiTac();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm mới thất bại!");
                e.printStackTrace();
            }
        }
    }

    // Xoá đối tác khỏi CSDL
    private void delete() {
        String message = "Các hàng hoá của đối tác đang lưu trữ trong kho sẽ bị xoá!"
                + "\nBạn có chắc chắn xoá đối tác này?";
        if (MsgBox.confirm(this, message)) {
            try {
                int rowModel = tblDoiTac.convertRowIndexToModel(this.row);
                int maDT = (int) tblDoiTac.getModel().getValueAt(rowModel, 1);
                dtDAO.delete(maDT);
                this.fillToTableDoiTac();
                this.clearForm();
                MsgBox.alert(this, "Xoá thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoá thất bại!");
                e.printStackTrace();
            }
        }
    }

    // Cập nhật thông tin đối tác vào CSDL
    private void update() {
        if (!isValidated()) {
            return;
        }
        DoiTac dt = getForm();
        try {
            dtDAO.update(dt);
            this.fillToTableDoiTac();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            e.printStackTrace();
        }
    }

    // Tạo tiêu đề và định dạng bảng
    private void formatTable() {
        String header[] = {"STT", "MÃ ĐỐI TÁC", "TÊN ĐỐI TÁC", "ĐỊA CHỈ", "EMAIL",
            "SỐ ĐIỆN THOẠI", "VAI TRÒ"};
        this.modelDoiTac = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            Class[] types = new Class[]{
                Integer.class, Integer.class, String.class, String.class,
                String.class, String.class, String.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };

        tblDoiTac.setAutoCreateRowSorter(true);
        tblDoiTac.setModel(modelDoiTac);
        tblDoiTac.removeColumn(tblDoiTac.getColumnModel().getColumn(1));
        tblDoiTac.getColumnModel().getColumn(0).setMaxWidth(40);

        tblDoiTac.setDefaultRenderer(Object.class, new DoiTacTableCellRenderer());

        DoiTacTableCellRenderer centerRenderer = new DoiTacTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblDoiTac.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblDoiTac.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tblDoiTac.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

    }

    class DoiTacTableCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            Color color = Color.black;
            Object obj = table.getValueAt(row, 5);
            if (obj != null && "Khách hàng".equals(obj.toString())) {
                color = new Color(19, 97, 91);
            }
            if (obj != null && "Nhà phân phối".equals(obj.toString())) {
                color = new Color(163, 52, 34);
            }
            if (isSelected) {
                color = Color.white;
            }
            setForeground(color);
            table.setSelectionBackground(new Color(38, 117, 191));
            return this;
        }
    }

    // Đỗ lại dữ liệu 
    public void refreshForm() {
        this.fillToComboBoxTimKiemDT();
        this.fillToTableDoiTac();

        this.timer.restart();
    }

    // sau hai phút tải lại dữ liệu
    private Timer timer = new Timer(300000, (e) -> {
        refreshForm();
    });

}
