/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stoman.ui;

import java.awt.*;
import java.awt.Component;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.border.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.google.zxing.WriterException;
import com.stoman.dao.ChiTietKiemKhoDAO;
import com.stoman.dao.HangHoaDAO;
import com.stoman.dao.KhoDAO;
import com.stoman.dao.LuuTruDAO;
import com.stoman.dao.NhanVienDAO;
import com.stoman.dao.PhieuKiemKhoDAO;
import com.stoman.dao.ProcedureDAO;
import com.stoman.entity.ChiTietKiemKho;
import com.stoman.entity.HangHoa;
import com.stoman.entity.Kho;
import com.stoman.entity.LuuTru;
import com.stoman.entity.NhanVien;
import com.stoman.entity.PhieuKiemKho;
import com.stoman.utils.Auth;
import com.stoman.utils.DateComparator;
import com.stoman.utils.DateTimeComparator;
import com.stoman.utils.MsgBox;
import com.stoman.utils.QRCode;
import com.stoman.utils.XReport;
import com.stoman.utils.TableNumberCellRenderer;
import com.stoman.utils.JSpinnerEditor;
import com.stoman.utils.LowerCaseStringConverter;
import com.stoman.utils.XDate;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import com.toedter.calendar.*;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Huy
 */
public class PhieuKiemKhoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form PhieuKiemKhoDialog
     */
    public PhieuKiemKhoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlBackground = new JPanel();
        tabs = new JTabbedPane();
        pnlChiTietPhieuKiem = new JPanel();
        pnlTblCTPhieu = new JScrollPane();
        tblCTPhieu = new JTable();
        pnlThongTin = new JPanel();
        lblTrangThai = new JLabel();
        lblKho = new JLabel();
        lblNgayLap = new JLabel();
        lblNgayKiem = new JLabel();
        lblNguoiLap = new JLabel();
        lblGhiChu = new JLabel();
        pnlTxtGhiChu = new JScrollPane();
        txtGhiChu = new JTextArea();
        chkHoanThanh = new JCheckBox();
        cboKho = new JComboBox<>();
        txtNguoiLap = new JTextField();
        txtNgayLap = new JFormattedTextField();
        txtNgayKiem = new JDateChooser();
        pnlTimKiemCT = new JPanel();
        txtTimKiemCT = new com.stoman.utils.JTextFieldCustom(defaultSearchHangHoa);
        lblTimKiemCT = new JLabel();
        lblTheoCT = new JLabel();
        cboTimKiemCT = new JComboBox<>();
        pnlNutDieuHuong = new JPanel();
        btnFirst = new JButton();
        btnPrev = new JButton();
        btnNext = new JButton();
        btnLast = new JButton();
        pnlChucNang = new JPanel();
        btnThem = new JButton();
        btnXoa = new JButton();
        btnHoanTac = new JButton();
        btnSua = new JButton();
        btnMoi = new JButton();
        btnChiTiet = new JButton();
        btnXuatMaPhieu = new JButton();
        pnlChucNangMoRong = new JPanel();
        btnXuatFile = new JButton();
        btnInPhieu = new JButton();
        pnlDanhSach = new JPanel();
        pnlTblPhieuKiemKho = new JScrollPane();
        tblPhieu = new JTable();
        pnlTimKiem = new JPanel();
        cboTimKiemPhieu = new JComboBox<>();
        lblTimKiemTheoPhieu = new JLabel();
        txtTimKiemPhieu = new com.stoman.utils.JTextFieldCustom(defaultSearchPhieu);
        lblTimKiemPhieu = new JLabel();
        ChiTietPhieuJDialog = new JDialog();
        pnlBackgroundCTP = new JPanel();
        tabsCTP = new JTabbedPane();
        pnlDSKiemKho = new JPanel();
        pnlTblCTPhieu_ChiTiet = new JScrollPane();
        tblCTPhieu_ChiTiet = new JTable();
        btnXoaKhoiDS = new JButton();
        txtTimKiemCTP = new com.stoman.utils.JTextFieldCustom(defaultSearchHangHoa);
        lblTimKiemCTP = new JLabel();
        pnlDSHangHoa = new JPanel();
        pnlTblHangHoaKho = new JScrollPane();
        tblHangHoaKho = new JTable();
        btnThemVaoDS = new JButton();
        lblTimKiemHHKho = new JLabel();
        txtTimKiemHHKho = new com.stoman.utils.JTextFieldCustom(defaultSearchHangHoa);
        QRCodeDialog = new JDialog();
        pnlBackgroundQR = new JPanel();
        lblQRCodeImage = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StoMan - Qu\u1ea3n l\u00fd phi\u1ebfu ki\u1ec3m kho");
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                formWindowClosed(e);
            }
        });
        var contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout());

        //======== pnlBackground ========
        {
            pnlBackground.setLayout(new BorderLayout());

            //======== tabs ========
            {

                //======== pnlChiTietPhieuKiem ========
                {
                    pnlChiTietPhieuKiem.setOpaque(false);

                    //======== pnlTblCTPhieu ========
                    {
                        pnlTblCTPhieu.setBorder(new TitledBorder(null, "Chi ti\u1ebft phi\u1ebfu", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                            new Font("Segoe UI", Font.BOLD, 13)));

                        //---- tblCTPhieu ----
                        tblCTPhieu.setModel(new DefaultTableModel(
                            new Object[][] {
                            },
                            new String[] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                            }
                        ) {
                            boolean[] columnEditable = new boolean[] {
                                true, false, true, true
                            };
                            @Override
                            public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return columnEditable[columnIndex];
                            }
                        });
                        tblCTPhieu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                        tblCTPhieu.addMouseListener(new MouseAdapter() {
                            @Override
                            public void mouseClicked(MouseEvent e) {
                                tblCTPhieuMouseClicked(e);
                            }
                        });
                        tblCTPhieu.addPropertyChangeListener(e -> tblCTPhieuPropertyChange(e));
                        tblCTPhieu.addKeyListener(new KeyAdapter() {
                            @Override
                            public void keyReleased(KeyEvent e) {
                                tblCTPhieuKeyReleased(e);
                            }
                        });
                        pnlTblCTPhieu.setViewportView(tblCTPhieu);
                    }

                    //======== pnlThongTin ========
                    {
                        pnlThongTin.setBorder(new TitledBorder(null, "Th\u00f4ng tin phi\u1ebfu", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                            new Font("Segoe UI", Font.BOLD, 13)));
                        pnlThongTin.setOpaque(false);

                        //---- lblTrangThai ----
                        lblTrangThai.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblTrangThai.setText("Tr\u1ea1ng th\u00e1i");

                        //---- lblKho ----
                        lblKho.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblKho.setText("Kho");

                        //---- lblNgayLap ----
                        lblNgayLap.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblNgayLap.setText("Ng\u00e0y l\u1eadp");

                        //---- lblNgayKiem ----
                        lblNgayKiem.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblNgayKiem.setText("Ng\u00e0y ki\u1ec3m");

                        //---- lblNguoiLap ----
                        lblNguoiLap.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblNguoiLap.setText("Ng\u01b0\u1eddi l\u1eadp");

                        //---- lblGhiChu ----
                        lblGhiChu.setFont(new Font("Segoe UI", Font.BOLD, 13));
                        lblGhiChu.setText("Ghi ch\u00fa");

                        //======== pnlTxtGhiChu ========
                        {

                            //---- txtGhiChu ----
                            txtGhiChu.setColumns(20);
                            txtGhiChu.setRows(5);
                            pnlTxtGhiChu.setViewportView(txtGhiChu);
                        }

                        //---- chkHoanThanh ----
                        chkHoanThanh.setText("Ho\u00e0n th\u00e0nh");

                        //---- cboKho ----
                        cboKho.setModel(new DefaultComboBoxModel<>(new String[] {

                        }));
                        cboKho.addItemListener(e -> cboKhoItemStateChanged(e));
                        cboKho.addActionListener(e -> cboKhoActionPerformed(e));

                        //---- txtNguoiLap ----
                        txtNguoiLap.setEditable(false);

                        //---- txtNgayLap ----
                        txtNgayLap.setEditable(false);

                        //---- txtNgayKiem ----
                        txtNgayKiem.setDate(new Date());
                        txtNgayKiem.setOpaque(false);

                        GroupLayout pnlThongTinLayout = new GroupLayout(pnlThongTin);
                        pnlThongTin.setLayout(pnlThongTinLayout);
                        pnlThongTinLayout.setHorizontalGroup(
                            pnlThongTinLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlThongTinLayout.createParallelGroup()
                                        .addComponent(lblNgayLap, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNguoiLap, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNgayKiem))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlThongTinLayout.createParallelGroup()
                                        .addComponent(txtNgayKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNguoiLap)
                                        .addComponent(txtNgayLap))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlThongTinLayout.createParallelGroup()
                                        .addComponent(lblKho, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTrangThai))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlThongTinLayout.createParallelGroup()
                                        .addGroup(pnlThongTinLayout.createSequentialGroup()
                                            .addComponent(cboKho, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblGhiChu))
                                        .addComponent(chkHoanThanh))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pnlTxtGhiChu)
                                    .addContainerGap())
                        );
                        pnlThongTinLayout.setVerticalGroup(
                            pnlThongTinLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(pnlTxtGhiChu, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(pnlThongTinLayout.createSequentialGroup()
                                            .addGroup(pnlThongTinLayout.createParallelGroup()
                                                .addGroup(pnlThongTinLayout.createSequentialGroup()
                                                    .addComponent(lblGhiChu)
                                                    .addGap(14, 14, 14))
                                                .addGroup(GroupLayout.Alignment.TRAILING, pnlThongTinLayout.createSequentialGroup()
                                                    .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNguoiLap)
                                                        .addComponent(lblNguoiLap)
                                                        .addComponent(lblKho)
                                                        .addComponent(cboKho, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblNgayLap)
                                                .addComponent(txtNgayLap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblTrangThai)
                                                .addComponent(chkHoanThanh))
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnlThongTinLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNgayKiem, GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                                .addComponent(lblNgayKiem, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addContainerGap())
                        );
                        pnlThongTinLayout.linkSize(SwingConstants.VERTICAL, new Component[] {txtNgayKiem, txtNgayLap});
                    }

                    //======== pnlTimKiemCT ========
                    {
                        pnlTimKiemCT.setOpaque(false);

                        //---- txtTimKiemCT ----
                        txtTimKiemCT.addKeyListener(new KeyAdapter() {
                            @Override
                            public void keyReleased(KeyEvent e) {
                                txtTimKiemCTKeyReleased(e);
                            }
                        });

                        //---- lblTimKiemCT ----
                        lblTimKiemCT.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                        //---- lblTheoCT ----
                        lblTheoCT.setText("theo");

                        //---- cboTimKiemCT ----
                        cboTimKiemCT.addActionListener(e -> cboTimKiemCTActionPerformed(e));

                        GroupLayout pnlTimKiemCTLayout = new GroupLayout(pnlTimKiemCT);
                        pnlTimKiemCT.setLayout(pnlTimKiemCTLayout);
                        pnlTimKiemCTLayout.setHorizontalGroup(
                            pnlTimKiemCTLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlTimKiemCTLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(lblTimKiemCT)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTimKiemCT)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTheoCT)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboTimKiemCT, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                        );
                        pnlTimKiemCTLayout.setVerticalGroup(
                            pnlTimKiemCTLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlTimKiemCTLayout.createSequentialGroup()
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlTimKiemCTLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTimKiemCT)
                                        .addGroup(pnlTimKiemCTLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTimKiemCT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTheoCT)
                                            .addComponent(cboTimKiemCT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap())
                        );
                    }

                    //======== pnlNutDieuHuong ========
                    {
                        pnlNutDieuHuong.setOpaque(false);
                        pnlNutDieuHuong.setLayout(new GridLayout());

                        //---- btnFirst ----
                        btnFirst.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/skip-to-start.png")));
                        btnFirst.setPreferredSize(new Dimension(100, 33));
                        btnFirst.addActionListener(e -> btnFirstActionPerformed(e));
                        pnlNutDieuHuong.add(btnFirst);

                        //---- btnPrev ----
                        btnPrev.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/double-left-24.png")));
                        btnPrev.setPreferredSize(new Dimension(100, 33));
                        btnPrev.addActionListener(e -> btnPrevActionPerformed(e));
                        pnlNutDieuHuong.add(btnPrev);

                        //---- btnNext ----
                        btnNext.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/double-right.png")));
                        btnNext.setPreferredSize(new Dimension(100, 33));
                        btnNext.addActionListener(e -> btnNextActionPerformed(e));
                        pnlNutDieuHuong.add(btnNext);

                        //---- btnLast ----
                        btnLast.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/skip-to-end.png")));
                        btnLast.setPreferredSize(new Dimension(100, 33));
                        btnLast.addActionListener(e -> btnLastActionPerformed(e));
                        pnlNutDieuHuong.add(btnLast);
                    }

                    //======== pnlChucNang ========
                    {
                        pnlChucNang.setBorder(new TitledBorder(null, "Ch\u1ee9c n\u0103ng", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                            new Font("Segoe UI", Font.BOLD, 13)));
                        pnlChucNang.setOpaque(false);
                        pnlChucNang.setLayout(new GridBagLayout());

                        //---- btnThem ----
                        btnThem.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_new_copy_32px.png")));
                        btnThem.setText("Th\u00eam chi ti\u1ebft");
                        btnThem.setPreferredSize(new Dimension(148, 45));
                        btnThem.addActionListener(e -> btnThemActionPerformed(e));
                        pnlChucNang.add(btnThem, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnXoa ----
                        btnXoa.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_delete_document_32px.png")));
                        btnXoa.setText("Xo\u00e1 phi\u1ebfu");
                        btnXoa.setPreferredSize(new Dimension(148, 45));
                        btnXoa.addActionListener(e -> btnXoaActionPerformed(e));
                        pnlChucNang.add(btnXoa, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnHoanTac ----
                        btnHoanTac.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_undo_32px.png")));
                        btnHoanTac.setText("Hu\u1ef7 thay \u0111\u1ed5i");
                        btnHoanTac.setPreferredSize(new Dimension(148, 45));
                        btnHoanTac.addActionListener(e -> btnHoanTacActionPerformed(e));
                        pnlChucNang.add(btnHoanTac, new GridBagConstraints(0, 4, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnSua ----
                        btnSua.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/edit-property-32.png")));
                        btnSua.setText("S\u1eeda phi\u1ebfu");
                        btnSua.setPreferredSize(new Dimension(148, 45));
                        btnSua.addActionListener(e -> btnSuaActionPerformed(e));
                        pnlChucNang.add(btnSua, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnMoi ----
                        btnMoi.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_document_32px.png")));
                        btnMoi.setText("Phi\u1ebfu m\u1edbi");
                        btnMoi.setPreferredSize(new Dimension(148, 45));
                        btnMoi.addActionListener(e -> btnMoiActionPerformed(e));
                        pnlChucNang.add(btnMoi, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnChiTiet ----
                        btnChiTiet.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/more-details-32.png")));
                        btnChiTiet.setText("Chi ti\u1ebft phi\u1ebfu");
                        btnChiTiet.setPreferredSize(new Dimension(148, 45));
                        btnChiTiet.addActionListener(e -> btnChiTietActionPerformed(e));
                        pnlChucNang.add(btnChiTiet, new GridBagConstraints(0, 5, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));

                        //---- btnXuatMaPhieu ----
                        btnXuatMaPhieu.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/icons8_qr_code_24px.png")));
                        btnXuatMaPhieu.setText("M\u00e3 phi\u1ebfu QR");
                        btnXuatMaPhieu.setPreferredSize(new Dimension(148, 45));
                        btnXuatMaPhieu.addActionListener(e -> btnXuatMaPhieuActionPerformed(e));
                        pnlChucNang.add(btnXuatMaPhieu, new GridBagConstraints(0, 6, 1, 1, 0.0, 0.0,
                            GridBagConstraints.CENTER, GridBagConstraints.NONE,
                            new Insets(0, 0, 0, 0), 8, 8));
                    }

                    //======== pnlChucNangMoRong ========
                    {
                        pnlChucNangMoRong.setOpaque(false);
                        pnlChucNangMoRong.setLayout(new GridLayout(1, 3));

                        //---- btnXuatFile ----
                        btnXuatFile.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/open-document.png")));
                        btnXuatFile.setText("Xu\u1ea5t file");
                        btnXuatFile.addActionListener(e -> btnXuatFileActionPerformed(e));
                        pnlChucNangMoRong.add(btnXuatFile);

                        //---- btnInPhieu ----
                        btnInPhieu.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/print.png")));
                        btnInPhieu.setText("In phi\u1ebfu");
                        btnInPhieu.addActionListener(e -> btnInPhieuActionPerformed(e));
                        pnlChucNangMoRong.add(btnInPhieu);
                    }

                    GroupLayout pnlChiTietPhieuKiemLayout = new GroupLayout(pnlChiTietPhieuKiem);
                    pnlChiTietPhieuKiem.setLayout(pnlChiTietPhieuKiemLayout);
                    pnlChiTietPhieuKiemLayout.setHorizontalGroup(
                        pnlChiTietPhieuKiemLayout.createParallelGroup()
                            .addGroup(pnlChiTietPhieuKiemLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlChiTietPhieuKiemLayout.createParallelGroup()
                                    .addComponent(pnlThongTin, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlChiTietPhieuKiemLayout.createSequentialGroup()
                                        .addGroup(pnlChiTietPhieuKiemLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlChiTietPhieuKiemLayout.createSequentialGroup()
                                                .addComponent(pnlNutDieuHuong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                                .addComponent(pnlChucNangMoRong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                            .addComponent(pnlTblCTPhieu)
                                            .addComponent(pnlTimKiemCT, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnlChucNang, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10))
                    );
                    pnlChiTietPhieuKiemLayout.setVerticalGroup(
                        pnlChiTietPhieuKiemLayout.createParallelGroup()
                            .addGroup(pnlChiTietPhieuKiemLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pnlThongTin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlChiTietPhieuKiemLayout.createParallelGroup()
                                    .addGroup(pnlChiTietPhieuKiemLayout.createSequentialGroup()
                                        .addComponent(pnlTimKiemCT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnlTblCTPhieu, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlChiTietPhieuKiemLayout.createParallelGroup()
                                            .addComponent(pnlChucNangMoRong, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pnlNutDieuHuong, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pnlChucNang, GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                    );
                }
                tabs.addTab("Th\u00f4ng tin phi\u1ebfu ki\u1ec3m", pnlChiTietPhieuKiem);

                //======== pnlDanhSach ========
                {
                    pnlDanhSach.setOpaque(false);

                    //======== pnlTblPhieuKiemKho ========
                    {
                        pnlTblPhieuKiemKho.setBorder(new TitledBorder(null, "Danh s\u00e1ch phi\u1ebfu", TitledBorder.LEADING, TitledBorder.DEFAULT_POSITION,
                            new Font("Segoe UI", Font.BOLD, 13)));

                        //---- tblPhieu ----
                        tblPhieu.setModel(new DefaultTableModel(
                            new Object[][] {
                            },
                            new String[] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                            }
                        ));
                        tblPhieu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                        tblPhieu.addMouseListener(new MouseAdapter() {
                            @Override
                            public void mouseClicked(MouseEvent e) {
                                tblPhieuMouseClicked(e);
                            }
                            @Override
                            public void mousePressed(MouseEvent e) {
                                tblPhieuMousePressed(e);
                            }
                        });
                        tblPhieu.addPropertyChangeListener(e -> tblPhieuPropertyChange(e));
                        pnlTblPhieuKiemKho.setViewportView(tblPhieu);
                    }

                    //======== pnlTimKiem ========
                    {
                        pnlTimKiem.setOpaque(false);

                        //---- cboTimKiemPhieu ----
                        cboTimKiemPhieu.addActionListener(e -> cboTimKiemPhieuActionPerformed(e));

                        //---- lblTimKiemTheoPhieu ----
                        lblTimKiemTheoPhieu.setText("theo");

                        //---- txtTimKiemPhieu ----
                        txtTimKiemPhieu.addKeyListener(new KeyAdapter() {
                            @Override
                            public void keyReleased(KeyEvent e) {
                                txtTimKiemPhieuKeyReleased(e);
                            }
                        });

                        //---- lblTimKiemPhieu ----
                        lblTimKiemPhieu.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                        GroupLayout pnlTimKiemLayout = new GroupLayout(pnlTimKiem);
                        pnlTimKiem.setLayout(pnlTimKiemLayout);
                        pnlTimKiemLayout.setHorizontalGroup(
                            pnlTimKiemLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlTimKiemLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblTimKiemPhieu)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTimKiemPhieu)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblTimKiemTheoPhieu)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboTimKiemPhieu, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                        );
                        pnlTimKiemLayout.setVerticalGroup(
                            pnlTimKiemLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlTimKiemLayout.createSequentialGroup()
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlTimKiemLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTimKiemPhieu)
                                        .addComponent(txtTimKiemPhieu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTimKiemTheoPhieu)
                                        .addComponent(cboTimKiemPhieu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap())
                        );
                    }

                    GroupLayout pnlDanhSachLayout = new GroupLayout(pnlDanhSach);
                    pnlDanhSach.setLayout(pnlDanhSachLayout);
                    pnlDanhSachLayout.setHorizontalGroup(
                        pnlDanhSachLayout.createParallelGroup()
                            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDanhSachLayout.createParallelGroup()
                                    .addComponent(pnlTblPhieuKiemKho, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                                    .addComponent(pnlTimKiem, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                    );
                    pnlDanhSachLayout.setVerticalGroup(
                        pnlDanhSachLayout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlTimKiem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlTblPhieuKiemKho, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                                .addContainerGap())
                    );
                }
                tabs.addTab("Danh s\u00e1ch phi\u1ebfu ki\u1ec3m", pnlDanhSach);
            }
            pnlBackground.add(tabs, BorderLayout.CENTER);
        }
        contentPane.add(pnlBackground, BorderLayout.CENTER);
        pack();
        setLocationRelativeTo(getOwner());

        //======== ChiTietPhieuJDialog ========
        {
            ChiTietPhieuJDialog.setTitle("Chi ti\u1ebft phi\u1ebfu ki\u1ec3m kho");
            ChiTietPhieuJDialog.setResizable(false);
            var ChiTietPhieuJDialogContentPane = ChiTietPhieuJDialog.getContentPane();
            ChiTietPhieuJDialogContentPane.setLayout(new BorderLayout());

            //======== pnlBackgroundCTP ========
            {
                pnlBackgroundCTP.setBackground(Color.white);
                pnlBackgroundCTP.setLayout(new BorderLayout());

                //======== tabsCTP ========
                {
                    tabsCTP.setOpaque(true);

                    //======== pnlDSKiemKho ========
                    {

                        //======== pnlTblCTPhieu_ChiTiet ========
                        {

                            //---- tblCTPhieu_ChiTiet ----
                            tblCTPhieu_ChiTiet.setModel(new DefaultTableModel(
                                new Object[][] {
                                },
                                new String[] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                                }
                            ));
                            tblCTPhieu_ChiTiet.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                            tblCTPhieu_ChiTiet.addMouseListener(new MouseAdapter() {
                                @Override
                                public void mouseClicked(MouseEvent e) {
                                    tblCTPhieu_ChiTietMouseClicked(e);
                                }
                            });
                            tblCTPhieu_ChiTiet.addKeyListener(new KeyAdapter() {
                                @Override
                                public void keyReleased(KeyEvent e) {
                                    tblCTPhieu_ChiTietKeyReleased(e);
                                }
                            });
                            pnlTblCTPhieu_ChiTiet.setViewportView(tblCTPhieu_ChiTiet);
                        }

                        //---- btnXoaKhoiDS ----
                        btnXoaKhoiDS.setText("X\u00f3a kh\u1ecfi danh s\u00e1ch");
                        btnXoaKhoiDS.setPreferredSize(new Dimension(139, 22));
                        btnXoaKhoiDS.addActionListener(e -> btnXoaKhoiDSActionPerformed(e));

                        //---- txtTimKiemCTP ----
                        txtTimKiemCTP.addKeyListener(new KeyAdapter() {
                            @Override
                            public void keyReleased(KeyEvent e) {
                                txtTimKiemCTPKeyReleased(e);
                            }
                        });

                        //---- lblTimKiemCTP ----
                        lblTimKiemCTP.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                        GroupLayout pnlDSKiemKhoLayout = new GroupLayout(pnlDSKiemKho);
                        pnlDSKiemKho.setLayout(pnlDSKiemKhoLayout);
                        pnlDSKiemKhoLayout.setHorizontalGroup(
                            pnlDSKiemKhoLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, pnlDSKiemKhoLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlDSKiemKhoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(pnlTblCTPhieu_ChiTiet, GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                                        .addGroup(pnlDSKiemKhoLayout.createSequentialGroup()
                                            .addComponent(lblTimKiemCTP)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTimKiemCTP)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnXoaKhoiDS, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap())
                        );
                        pnlDSKiemKhoLayout.setVerticalGroup(
                            pnlDSKiemKhoLayout.createParallelGroup()
                                .addGroup(pnlDSKiemKhoLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlDSKiemKhoLayout.createParallelGroup()
                                        .addComponent(lblTimKiemCTP, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoaKhoiDS, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTimKiemCTP))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pnlTblCTPhieu_ChiTiet, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                    .addContainerGap())
                        );
                    }
                    tabsCTP.addTab("Danh s\u00e1ch ki\u1ec3m kho", pnlDSKiemKho);

                    //======== pnlDSHangHoa ========
                    {

                        //======== pnlTblHangHoaKho ========
                        {

                            //---- tblHangHoaKho ----
                            tblHangHoaKho.setModel(new DefaultTableModel(
                                new Object[][] {
                                },
                                new String[] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                                }
                            ));
                            tblHangHoaKho.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                            pnlTblHangHoaKho.setViewportView(tblHangHoaKho);
                        }

                        //---- btnThemVaoDS ----
                        btnThemVaoDS.setText("Th\u00eam v\u00e0o danh s\u00e1ch");
                        btnThemVaoDS.addActionListener(e -> btnThemVaoDSActionPerformed(e));

                        //---- lblTimKiemHHKho ----
                        lblTimKiemHHKho.setIcon(new ImageIcon(getClass().getResource("/com/stoman/icons/search_24px.png")));

                        //---- txtTimKiemHHKho ----
                        txtTimKiemHHKho.addKeyListener(new KeyAdapter() {
                            @Override
                            public void keyReleased(KeyEvent e) {
                                txtTimKiemHHKhoKeyReleased(e);
                            }
                        });

                        GroupLayout pnlDSHangHoaLayout = new GroupLayout(pnlDSHangHoa);
                        pnlDSHangHoa.setLayout(pnlDSHangHoaLayout);
                        pnlDSHangHoaLayout.setHorizontalGroup(
                            pnlDSHangHoaLayout.createParallelGroup()
                                .addGroup(pnlDSHangHoaLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlDSHangHoaLayout.createParallelGroup()
                                        .addComponent(pnlTblHangHoaKho, GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                                        .addGroup(pnlDSHangHoaLayout.createSequentialGroup()
                                            .addComponent(lblTimKiemHHKho)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTimKiemHHKho)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnThemVaoDS)))
                                    .addContainerGap())
                        );
                        pnlDSHangHoaLayout.setVerticalGroup(
                            pnlDSHangHoaLayout.createParallelGroup()
                                .addGroup(pnlDSHangHoaLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlDSHangHoaLayout.createParallelGroup()
                                        .addComponent(lblTimKiemHHKho, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTimKiemHHKho)
                                        .addComponent(btnThemVaoDS, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pnlTblHangHoaKho, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                    .addContainerGap())
                        );
                    }
                    tabsCTP.addTab("Danh s\u00e1ch h\u00e0ng h\u00f3a trong kho", pnlDSHangHoa);
                }
                pnlBackgroundCTP.add(tabsCTP, BorderLayout.CENTER);
            }
            ChiTietPhieuJDialogContentPane.add(pnlBackgroundCTP, BorderLayout.CENTER);
        }

        //======== QRCodeDialog ========
        {
            QRCodeDialog.setTitle("Xu\u1ea5t m\u00e3 phi\u1ebfu (QR Code)");
            QRCodeDialog.setResizable(false);
            var QRCodeDialogContentPane = QRCodeDialog.getContentPane();
            QRCodeDialogContentPane.setLayout(new BorderLayout());

            //======== pnlBackgroundQR ========
            {
                pnlBackgroundQR.setPreferredSize(new Dimension(300, 300));
                pnlBackgroundQR.setLayout(new GridBagLayout());

                //---- lblQRCodeImage ----
                lblQRCodeImage.setBorder(new LineBorder(new Color(0x999999), 2));
                lblQRCodeImage.setPreferredSize(new Dimension(200, 200));
                pnlBackgroundQR.add(lblQRCodeImage, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
                    GridBagConstraints.CENTER, GridBagConstraints.NONE,
                    new Insets(0, 0, 0, 0), 0, 0));
            }
            QRCodeDialogContentPane.add(pnlBackgroundQR, BorderLayout.CENTER);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMouseClicked
        if (evt.getClickCount() < 2 || tblPhieu.getSelectedColumn() == 3) {
            return;
        }
        this.rowPhieu = tblPhieu.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblPhieuMouseClicked

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        this.ChiTietPhieuJDialog.setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnThemVaoDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoDSActionPerformed
        // TODO add your handling code here:
        this.insertCT();
    }//GEN-LAST:event_btnThemVaoDSActionPerformed

    private void btnXoaKhoiDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoiDSActionPerformed
        // TODO add your handling code here:
        this.deleteCT();
    }//GEN-LAST:event_btnXoaKhoiDSActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insertPhieu();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.deletePhieu();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.updatePhieu();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
        this.fillToTableHHkho();
        btnChiTiet.setEnabled(true);
        tabsCTP.setSelectedIndex(1);
        ChiTietPhieuJDialog.setVisible(true);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void cboKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhoItemStateChanged
        // TODO add your handling code here:
        this.fillToTableCTPhieu();
        this.fillToTableHHkho();
    }//GEN-LAST:event_cboKhoItemStateChanged

    private void btnXuatMaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatMaPhieuActionPerformed
        // TODO add your handling code here:
        createQRCode();
    }//GEN-LAST:event_btnXuatMaPhieuActionPerformed

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // TODO add your handling code here:
        exportReportExcel();
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnInPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInPhieuActionPerformed
        // TODO add your handling code here:
        printReport();
    }//GEN-LAST:event_btnInPhieuActionPerformed

    private void cboKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoActionPerformed
        // TODO add your handling code here:
        cboKho.setEnabled(!isUpdate);
    }//GEN-LAST:event_cboKhoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.timer.stop();
    }//GEN-LAST:event_formWindowClosed
    private void txtTimKiemCTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemCTKeyReleased
        // TODO add your handling code here:
        searchCTPhieu();
    }//GEN-LAST:event_txtTimKiemCTKeyReleased

    private void cboTimKiemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimKiemCTActionPerformed
        // TODO add your handling code here:
        txtTimKiemCT.setText(defaultSearchHangHoa);
        searchCTPhieu();
    }//GEN-LAST:event_cboTimKiemCTActionPerformed

    private void txtTimKiemPhieuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemPhieuKeyReleased
        // TODO add your handling code here:
        searchPhieu();
    }//GEN-LAST:event_txtTimKiemPhieuKeyReleased

    private void cboTimKiemPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimKiemPhieuActionPerformed
        // TODO add your handling code here:
        txtTimKiemPhieu.setText(defaultSearchPhieu);
        searchPhieu();
    }//GEN-LAST:event_cboTimKiemPhieuActionPerformed

    private void txtTimKiemCTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemCTPKeyReleased
        // TODO add your handling code here:
        searchCTPhieu_ChiTiet();
    }//GEN-LAST:event_txtTimKiemCTPKeyReleased

    private void txtTimKiemHHKhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHHKhoKeyReleased
        // TODO add your handling code here:
        searchHangHoaKho();
    }//GEN-LAST:event_txtTimKiemHHKhoKeyReleased

    private void tblPhieuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblPhieuPropertyChange
        // TODO add your handling code here:
        if (rowPhieu < 0) {
            return;
        }
        if ("tableCellEditor".equals(evt.getPropertyName())) {
            updateTrangThaiPhieu();
        }
    }//GEN-LAST:event_tblPhieuPropertyChange

    private void tblPhieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMousePressed
        // TODO add your handling code here:
        this.rowPhieu = tblPhieu.getSelectedRow();
    }//GEN-LAST:event_tblPhieuMousePressed

    private void tblCTPhieu_ChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTPhieu_ChiTietMouseClicked
        // TODO add your handling code here:
        this.rowCTPhieu = tblCTPhieu_ChiTiet.getSelectedRow();
        mapSelectionTable(tblCTPhieu_ChiTiet, tblCTPhieu);
    }//GEN-LAST:event_tblCTPhieu_ChiTietMouseClicked

    private void tblCTPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTPhieuMouseClicked
        // TODO add your handling code here:
        this.rowCTPhieu = tblCTPhieu.getSelectedRow();
        mapSelectionTable(tblCTPhieu, tblCTPhieu_ChiTiet);
    }//GEN-LAST:event_tblCTPhieuMouseClicked

    private void tblCTPhieuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCTPhieuKeyReleased
        // TODO add your handling code here:
        disableEnterCellNextLine(tblCTPhieu);
        //updateSoLuongThuc(tblCTPhieu, tblCTPhieu.getSelectedRow());
    }//GEN-LAST:event_tblCTPhieuKeyReleased

    private void tblCTPhieu_ChiTietKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCTPhieu_ChiTietKeyReleased
        // TODO add your handling code here:
        disableEnterCellNextLine(tblCTPhieu_ChiTiet);
        //updateSoLuongThuc(tblCTPhieu_ChiTiet, tblCTPhieu_ChiTiet.getSelectedRow());
    }//GEN-LAST:event_tblCTPhieu_ChiTietKeyReleased

    private void tblCTPhieuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblCTPhieuPropertyChange
        // TODO add your handling code here:
        /*
        if(tblCTPhieu.getSelectedRow() >= 0) {
            updateSoLuongThuc(tblCTPhieu, tblCTPhieu.getSelectedRow());
        }
        */
    }//GEN-LAST:event_tblCTPhieuPropertyChange

    private void btnHoanTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanTacActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_btnHoanTacActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuKiemKhoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PhieuKiemKhoJDialog dialog = new PhieuKiemKhoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel pnlBackground;
    private JTabbedPane tabs;
    private JPanel pnlChiTietPhieuKiem;
    private JScrollPane pnlTblCTPhieu;
    private JTable tblCTPhieu;
    private JPanel pnlThongTin;
    private JLabel lblTrangThai;
    private JLabel lblKho;
    private JLabel lblNgayLap;
    private JLabel lblNgayKiem;
    private JLabel lblNguoiLap;
    private JLabel lblGhiChu;
    private JScrollPane pnlTxtGhiChu;
    private JTextArea txtGhiChu;
    private JCheckBox chkHoanThanh;
    private JComboBox<String> cboKho;
    private JTextField txtNguoiLap;
    private JFormattedTextField txtNgayLap;
    private JDateChooser txtNgayKiem;
    private JPanel pnlTimKiemCT;
    private JTextField txtTimKiemCT;
    private JLabel lblTimKiemCT;
    private JLabel lblTheoCT;
    private JComboBox<String> cboTimKiemCT;
    private JPanel pnlNutDieuHuong;
    private JButton btnFirst;
    private JButton btnPrev;
    private JButton btnNext;
    private JButton btnLast;
    private JPanel pnlChucNang;
    private JButton btnThem;
    private JButton btnXoa;
    private JButton btnHoanTac;
    private JButton btnSua;
    private JButton btnMoi;
    private JButton btnChiTiet;
    private JButton btnXuatMaPhieu;
    private JPanel pnlChucNangMoRong;
    private JButton btnXuatFile;
    private JButton btnInPhieu;
    private JPanel pnlDanhSach;
    private JScrollPane pnlTblPhieuKiemKho;
    private JTable tblPhieu;
    private JPanel pnlTimKiem;
    private JComboBox<String> cboTimKiemPhieu;
    private JLabel lblTimKiemTheoPhieu;
    private JTextField txtTimKiemPhieu;
    private JLabel lblTimKiemPhieu;
    private JDialog ChiTietPhieuJDialog;
    private JPanel pnlBackgroundCTP;
    private JTabbedPane tabsCTP;
    private JPanel pnlDSKiemKho;
    private JScrollPane pnlTblCTPhieu_ChiTiet;
    private JTable tblCTPhieu_ChiTiet;
    private JButton btnXoaKhoiDS;
    private JTextField txtTimKiemCTP;
    private JLabel lblTimKiemCTP;
    private JPanel pnlDSHangHoa;
    private JScrollPane pnlTblHangHoaKho;
    private JTable tblHangHoaKho;
    private JButton btnThemVaoDS;
    private JLabel lblTimKiemHHKho;
    private JTextField txtTimKiemHHKho;
    private JDialog QRCodeDialog;
    private JPanel pnlBackgroundQR;
    private JLabel lblQRCodeImage;
    // End of variables declaration//GEN-END:variables

    private KhoDAO kDAO = new KhoDAO();
    private HangHoaDAO hhDAO = new HangHoaDAO();
    private PhieuKiemKhoDAO pkkDAO = new PhieuKiemKhoDAO();
    private ChiTietKiemKhoDAO ctkkDAO = new ChiTietKiemKhoDAO();
    private LuuTruDAO ltDAO = new LuuTruDAO();
    private ProcedureDAO spDAO = new ProcedureDAO();
    private NhanVienDAO nvDAO = new NhanVienDAO();

    private DefaultTableModel modelPhieu;
    private DefaultTableModel modelCTPhieuKiem;
    private DefaultTableModel modelHangHoaKho;

    private ArrayList<Integer> listCT = new ArrayList<>();
    private TableRowSorter<TableModel> sorterPhieu;
    private TableRowSorter<TableModel> sorterCTPhieu;
    private TableRowSorter<TableModel> sorterCTPhieu_ChiTiet;
    private TableRowSorter<TableModel> sorterHHKho;

    private String dateFormat = "dd-MM-yyyy";
    private String dateTimeFormat = "dd-MM-yyyy HH:mm:ss";

    private int rowPhieu = -1;
    private int rowCTPhieu = -1;

    private String defaultSearchHangHoa = "Nhập từ khoá tìm kiếm hàng hoá";
    private String defaultSearchPhieu = "Nhập từ khoá tìm kiếm phiếu";

    private boolean isUpdate = false;

    private void init() {
        this.setLocationRelativeTo(null);
        this.setModal(false);
        this.initDialogOther();
        
        this.formatTable();
        this.fillToComboBoxTimKiemPhieu();
        this.fillToComboBoxTimKiemCT();
        this.fillToComboBoxKho();
        this.fillToTablePhieu();
        this.fillToTableHHkho();

        tabs.setSelectedIndex(1);

        this.updateStatus();

        timer.start();
    }
    

    private void initDialogOther() {
        ChiTietPhieuJDialog.pack();
        ChiTietPhieuJDialog.setLocationRelativeTo(null);
        ChiTietPhieuJDialog.setModalityType(ModalityType.APPLICATION_MODAL);
        ChiTietPhieuJDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        QRCodeDialog.pack();
        QRCodeDialog.setLocationRelativeTo(null);
        QRCodeDialog.setModalityType(ModalityType.APPLICATION_MODAL);
        QRCodeDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    // Đổ dữ liệu vào ComboBox kho
    private void fillToComboBoxKho() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            List<Kho> list = kDAO.selectAll();
            for (Kho k : list) {
                model.addElement(k);
            }
            cboKho.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Đổ dữ liệu vào bảng phiếu kiểm
    private SwingWorker workerPhieu;

    private void fillToTablePhieu() {

        if (workerPhieu != null) {
            workerPhieu.cancel(true);
        }
        modelPhieu.setRowCount(0);
        try {
            workerPhieu = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    Thread.sleep(100);
                    List<PhieuKiemKho> list = pkkDAO.selectAll();
                    int i = 1;
                    for (PhieuKiemKho pkk : list) {
                        if (isCancelled()) {
                            break;
                        }
                        int maLT = ctkkDAO.getOnlyOneMaLT(pkk.getMaKK());
                        if (maLT == 0) {
                            continue;
                        }
                        int maKho = ltDAO.getMaKho(maLT);
                        NhanVien nv = nvDAO.selectByID(pkk.getMaNV());
                        modelPhieu.addRow(new Object[]{
                            i++,
                            maKho,
                            XDate.toString(pkk.getNgayKiem(), dateFormat),
                            pkk.isTrangThai(),
                            nv.getTenNV(),
                            XDate.toString(pkk.getNgayLap(), dateTimeFormat),
                            pkk.getMaKK()
                        });
                    }
                    if (isCancelled()) {
                        modelPhieu.setRowCount(0);
                    }
                    return null;
                }

                @Override
                protected void done() {
                    if (rowPhieu < 0) {
                        return;
                    }
                    tblPhieu.setRowSelectionInterval(rowPhieu, rowPhieu);
                }

            };
            workerPhieu.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Đỗ dữ liệu vào bảng chi tiết
    private SwingWorker workerCTPhieu;

    private void fillToTableCTPhieu() {
        if (workerCTPhieu != null) {
            workerCTPhieu.cancel(true);
        }
        modelCTPhieuKiem.setRowCount(0);
        listCT.clear();
        String maPhieu = tblCTPhieu.getToolTipText();
        if (maPhieu == null) {
            return;
        }

        try {
            workerCTPhieu = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    Thread.sleep(100);
                    List<ChiTietKiemKho> list = ctkkDAO.selectByMaPhieu(Integer.parseInt(maPhieu));
                    int i = 1;
                    for (ChiTietKiemKho ctkk : list) {
                        if (isCancelled()) {
                            break;
                        }
                        listCT.add(ctkk.getMaLT());
                        LuuTru lt = ltDAO.selectByID(ctkk.getMaLT());
                        HangHoa hh = hhDAO.selectByID(lt.getMaHH());
                        modelCTPhieuKiem.addRow(new Object[]{
                            i++,
                            hh,
                            ctkk.getSoLuongTon(),
                            ctkk.getSoLuongThuc(),
                            ctkk.getMaCTKK(),
                            ctkk.getMaLT()
                        });
                    }
                    if (isCancelled()) {
                        modelCTPhieuKiem.setRowCount(0);
                    }

                    return null;
                }

                @Override
                protected void done() {
                    fillToTableHHkho();
                }

            };
            workerCTPhieu.execute();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Đỗ dữ liệu vào bảng hàng hóa trong kho
    private SwingWorker workerHHKho;
    private void fillToTableHHkho() {
        if (workerHHKho != null) {
            workerHHKho.cancel(true);
        }
        modelHangHoaKho.setRowCount(0);
        //String keyword
        if (cboKho.getItemCount() == 0) return;
        int maKho = ((Kho) cboKho.getSelectedItem()).getMaKho();
        try {
            workerHHKho = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    Thread.sleep(100);
                    List<LuuTru> list = ltDAO.selectNotInList(maKho, listCT);
                    int i = 1;
                    for (LuuTru lt : list) {
                        if (isCancelled()) {
                            break;
                        }
                        HangHoa hh = hhDAO.selectByID(lt.getMaHH());
                        modelHangHoaKho.addRow(new Object[]{
                            i++,
                            hh,
                            lt.getSoLuong(),
                            lt.getMaLT()
                        });
                    }
                    if (isCancelled()) {
                        modelHangHoaKho.setRowCount(0);
                    }
                    return null;
                }
            };
            workerHHKho.execute();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Lấy dữ liệu từ form phiếu nhập
    private PhieuKiemKho getFormPhieu() {
        PhieuKiemKho pkk = new PhieuKiemKho();
        pkk.setMaNV(txtNguoiLap.getToolTipText());
        pkk.setNgayKiem(txtNgayKiem.getDate());
        pkk.setNgayLap(XDate.toDate(txtNgayLap.getText(), dateTimeFormat));
        pkk.setTrangThai(chkHoanThanh.isSelected());
        pkk.setGhiChu(txtGhiChu.getText());

        return pkk;
    }

    // Nhập dữ liệu vào form phiếu nhập
    private void setFormPhieu(PhieuKiemKho pkk) {
        int rowPhieuModel = tblPhieu.convertRowIndexToModel(rowPhieu);
        int maKho = (int) modelPhieu.getValueAt(rowPhieuModel, 1);
        Kho k = kDAO.selectByID(maKho);
        NhanVien nv = nvDAO.selectByID(pkk.getMaNV());

        txtNguoiLap.setText(nv.getTenNV());
        txtNguoiLap.setToolTipText(pkk.getMaNV());
        txtNgayKiem.setDate(pkk.getNgayLap());
        txtNgayLap.setText(XDate.toString(pkk.getNgayLap(), dateTimeFormat));
        cboKho.getModel().setSelectedItem(k);
        chkHoanThanh.setSelected(pkk.isTrangThai());
        txtGhiChu.setText(pkk.getGhiChu());

        tblCTPhieu.setToolTipText(String.valueOf(pkk.getMaKK()));

        this.fillToTableCTPhieu();
    }

    // Thêm hàng hóa vào bảng Chi tiết
    private void insertCT() {
        if (tblHangHoaKho.getSelectedRow() < 0) {
            MsgBox.alert(this, "Chọn một hàng hoá muốn thêm!");
            return;
        }
        
        int selectRow = tblHangHoaKho.convertRowIndexToModel(tblHangHoaKho.getSelectedRow());
        int maLT = (Integer) modelHangHoaKho.getValueAt(selectRow, 3);
        modelCTPhieuKiem.addRow(new Object[]{
            tblCTPhieu_ChiTiet.getRowCount() + 1,
            (HangHoa) modelHangHoaKho.getValueAt(selectRow, 1),
            (Double) modelHangHoaKho.getValueAt(selectRow, 2),
            0.0,
            0,
            maLT
        });

        this.listCT.add(maLT);
        this.fillToTableHHkho();
    }

    // Xóa hàng hóa khỏi chi tiết
    private ArrayList<ChiTietKiemKho> delCTP = new ArrayList<>();

    private void deleteCT() {
        if (tblCTPhieu_ChiTiet.getSelectedRow() < 0) {
            MsgBox.alert(this, "Chọn một hàng hoá muốn xoá!");
            return;
        }
        
        int delRow = tblCTPhieu_ChiTiet.convertRowIndexToModel(tblCTPhieu_ChiTiet.getSelectedRow());
        ChiTietKiemKho ctkk = this.getFormCTPhieu(delRow);

        if (isUpdate && ctkk.getMaLT() != 0) {
            delCTP.add(ctkk);
            this.listCT.remove(new Integer(ctkk.getMaLT()));
        }
        
        modelCTPhieuKiem.removeRow(delRow);

        for (int i = 0; i < modelCTPhieuKiem.getRowCount(); i++) {
            modelCTPhieuKiem.setValueAt(i + 1, i, 0);
        }

        this.fillToTableHHkho();
    }

    // Lấy dữ liệu từ form chi tiết phiếu
    private ChiTietKiemKho getFormCTPhieu(int row) {
        ChiTietKiemKho ctkk = new ChiTietKiemKho();

        ctkk.setSoLuongTon((double) modelCTPhieuKiem.getValueAt(row, 2));
        ctkk.setSoLuongThuc((double) modelCTPhieuKiem.getValueAt(row, 3));

        ctkk.setMaCTKK((Integer) modelCTPhieuKiem.getValueAt(row, 4));
        ctkk.setMaLT((Integer) modelCTPhieuKiem.getValueAt(row, 5));

        return ctkk;
    }

    // Nhập phiếu kiểm mới vào hệ thống và cập nhật thông tin hàng hóa
    private void insertPhieu() {
        if (!isValidated()) {
            return;
        }
        PhieuKiemKho pkk = this.getFormPhieu();
        ChiTietKiemKho ctkk;
        pkkDAO.insert(pkk);

        int maKK = pkkDAO.getMaPhieuByNVandCreatedDate(pkk.getMaNV(), pkk.getNgayLap());

        int rows = modelCTPhieuKiem.getRowCount();

        if (rows < 1) {
            MsgBox.alert(this, "Danh sách hàng hoá kiểm trống!");
            return;
        }

        for (int i = 0; i < rows; i++) {
            ctkk = getFormCTPhieu(i);

            spDAO.insertPhieuKiem(ctkk, maKK);
        }

        this.clearForm();
        this.fillToTablePhieu();

        this.updateStatus();
        MsgBox.alert(this, "Thêm phiếu kiểm thành công!");
    }

    // Cập nhật phiếu vào hệ thống và cập nhật thông tin hàng hóa
    private void updatePhieu() {
        if (!isValidated()) {
            return;
        }
        PhieuKiemKho pkk = this.getFormPhieu();
        String maKK = tblCTPhieu.getToolTipText();

        if (maKK == null) {
            return;
        }

        pkk.setMaKK(Integer.valueOf(maKK));
        pkkDAO.update(pkk);

        ChiTietKiemKho ctkk;
        int rows = modelCTPhieuKiem.getRowCount();
        for (int i = 0; i < rows; i++) {
            ctkk = getFormCTPhieu(i);

            if (ctkk.getMaCTKK() != 0) {
                spDAO.updatePhieuKiem(ctkk);
            } else {
                spDAO.insertPhieuKiem(ctkk, pkk.getMaKK());
            }
        }
        for (ChiTietKiemKho ctpkDel : delCTP) {
            spDAO.deletePhieuKiem(ctpkDel);
        }

        this.fillToTablePhieu();
        this.fillToTableCTPhieu();

        MsgBox.alert(this, "Cập nhật phiếu kiểm thành công!");
    }

    private void updateTrangThaiPhieu() {
        boolean isHoanThanh = (boolean) modelPhieu.getValueAt(rowPhieu, 3);
        int maPhieu = (int) modelPhieu.getValueAt(rowPhieu, 6);
        PhieuKiemKho pkk = pkkDAO.selectByID(maPhieu);
        pkk.setTrangThai(isHoanThanh);
        pkkDAO.update(pkk);
    }
    
    private void updateSoLuongThuc(JTable table, int row) {
        Double soLuongThuc = (Double) table.getValueAt(row, 3);
        int maChiTiet = (int) table.getModel().getValueAt(table.convertRowIndexToModel(row), 4);
        ChiTietKiemKho ctkk = ctkkDAO.selectByID(maChiTiet);
        ctkk.setSoLuongThuc(soLuongThuc);
        ctkkDAO.update(ctkk);
    }

    // Xóa phiếu kiểm khỏi hệ thống
    private void deletePhieu() {
        String maKK = tblCTPhieu.getToolTipText();

        if (maKK == null) {
            return;
        }

        int rows = modelCTPhieuKiem.getRowCount();
        ChiTietKiemKho ctpk;
        for (ChiTietKiemKho ctpkDel : delCTP) {
            spDAO.deletePhieuKiem(ctpkDel);
        }
        for (int i = 0; i < rows; i++) {
            ctpk = getFormCTPhieu(i);
            if (ctpk.getMaCTKK() != 0) {
                spDAO.deletePhieuKiem(ctpk);
            }
        }

        pkkDAO.delete(Integer.valueOf(maKK));

        this.clearForm();
        this.fillToTablePhieu();

        MsgBox.alert(this, "Xóa phiếu kiểm thành công!");
    }

    // Xóa trắng form
    private void clearForm() {
        Date NgayLap = new Date(System.currentTimeMillis());
        
        txtNguoiLap.setToolTipText(Auth.user.getMaNV());
        txtNguoiLap.setText(Auth.user.getTenNV());
        txtNgayLap.setText(XDate.toString(NgayLap, dateTimeFormat));
        txtGhiChu.setText(null);
        tblCTPhieu.setToolTipText(null);
        txtNgayKiem.setDate(new Date());
        chkHoanThanh.setSelected(false);
        if (cboKho.getItemCount() > 0){
            cboKho.setSelectedIndex(0);
        }
        
        this.fillToTableCTPhieu();

        isUpdate = false;

        this.rowPhieu = -1;
        this.rowCTPhieu = -1;

        this.updateStatus();
    }

    private void formatTable() {
        String[] headerPhieuKiem = {"STT", "KHO", "NGÀY KIỂM", "HOÀN THÀNH", "NGƯỜI LẬP", "NGÀY LẬP", "MÃ PHIẾU"};
        this.modelPhieu = new DefaultTableModel(headerPhieuKiem, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 3) {
                    return true;
                }
                return false;
            }

            Class[] types = new Class[]{
                Integer.class, Integer.class, String.class, Boolean.class,
                String.class, String.class, Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                //return getValueAt(0, columnIndex).getClass();
                return types[columnIndex];
            }
        };

        String[] headerCTPhieuKiem = {"STT", "HÀNG HOÁ", "SỐ LƯỢNG TỒN", "SỐ LƯỢNG THỰC", "MÃ CHI TIẾT", "MÃ LƯU TRỮ"};
        this.modelCTPhieuKiem = new DefaultTableModel(headerCTPhieuKiem, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 3) {
                    return true;
                }
                return false;
            }

            Class[] types = new Class[]{
                Integer.class, HangHoa.class, Integer.class, Integer.class,
                Integer.class, Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };

        String[] headerHangHoaKho = {"STT", "HÀNG HOÁ", "SỐ LƯỢNG TỒN", "LƯU TRỮ"};
        this.modelHangHoaKho = new DefaultTableModel(headerHangHoaKho, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            Class[] types = new Class[]{
                Integer.class, HangHoa.class, Integer.class, Integer.class,
                Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };

        tblPhieu.setModel(modelPhieu);
        tblCTPhieu_ChiTiet.setModel(modelCTPhieuKiem);
        tblCTPhieu.setModel(modelCTPhieuKiem);
        tblHangHoaKho.setModel(modelHangHoaKho);
        
        // Cài đặt bộ lọc cho bảng
        sorterPhieu = new TableRowSorter<>(modelPhieu);
        sorterPhieu.setStringConverter(new LowerCaseStringConverter());
        sorterPhieu.setComparator(2, new DateComparator(dateFormat));
        sorterPhieu.setComparator(5, new DateTimeComparator(dateTimeFormat));

        sorterCTPhieu = new TableRowSorter<>(modelCTPhieuKiem);
        sorterCTPhieu.setStringConverter(new LowerCaseStringConverter());

        sorterCTPhieu_ChiTiet = new TableRowSorter<>(modelCTPhieuKiem);
        sorterCTPhieu_ChiTiet.setStringConverter(new LowerCaseStringConverter());

        sorterHHKho = new TableRowSorter<>(modelHangHoaKho);
        sorterHHKho.setStringConverter(new LowerCaseStringConverter());

        tblPhieu.setRowSorter(sorterPhieu);
        tblCTPhieu.setRowSorter(sorterCTPhieu);
        tblCTPhieu_ChiTiet.setRowSorter(sorterCTPhieu_ChiTiet);
        tblHangHoaKho.setRowSorter(sorterHHKho);

        // Giấu cột
        tblPhieu.getColumnModel().removeColumn(tblPhieu.getColumnModel().getColumn(6));
        tblCTPhieu_ChiTiet.getColumnModel().removeColumn(tblCTPhieu_ChiTiet.getColumnModel().getColumn(5));
        tblCTPhieu_ChiTiet.getColumnModel().removeColumn(tblCTPhieu_ChiTiet.getColumnModel().getColumn(4));
        tblCTPhieu.getColumnModel().removeColumn(tblCTPhieu.getColumnModel().getColumn(5));
        tblCTPhieu.getColumnModel().removeColumn(tblCTPhieu.getColumnModel().getColumn(4));
        tblHangHoaKho.getColumnModel().removeColumn(tblHangHoaKho.getColumnModel().getColumn(3));

        // Chỉnh độ rộng hàng trong bảng
        tblPhieu.setRowHeight(25);
        tblCTPhieu_ChiTiet.setRowHeight(25);
        tblCTPhieu.setRowHeight(25);

        // Thêm chức năng nhập cho bảng
        JSpinnerEditor spinnerEditor = new JSpinnerEditor(0.0, 0.0, 10000000.0, 1.0);
        
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(3).setCellEditor(spinnerEditor);
        tblCTPhieu.getColumnModel().getColumn(3).setCellEditor(spinnerEditor);

        // Chỉnh size cột các bảng
        tblCTPhieu.getColumnModel().getColumn(0).setPreferredWidth(47);
        tblCTPhieu.getColumnModel().getColumn(1).setPreferredWidth(400);
        tblCTPhieu.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblCTPhieu.getColumnModel().getColumn(3).setPreferredWidth(120);

        tblHangHoaKho.getColumnModel().getColumn(0).setPreferredWidth(46);
        tblHangHoaKho.getColumnModel().getColumn(1).setPreferredWidth(380);
        tblHangHoaKho.getColumnModel().getColumn(2).setPreferredWidth(150);

        tblCTPhieu_ChiTiet.getColumnModel().getColumn(0).setPreferredWidth(46);
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(1).setPreferredWidth(330);
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(3).setPreferredWidth(100);

        tblPhieu.getColumnModel().getColumn(0).setPreferredWidth(46);
        tblPhieu.getColumnModel().getColumn(1).setPreferredWidth(46);
        tblPhieu.getColumnModel().getColumn(2).setPreferredWidth(185);
        tblPhieu.getColumnModel().getColumn(3).setPreferredWidth(185);
        tblPhieu.getColumnModel().getColumn(4).setPreferredWidth(185);
        tblPhieu.getColumnModel().getColumn(5).setPreferredWidth(186);

        // Định dạng form
        tblCTPhieu.getColumnModel().getColumn(0).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblCTPhieu.getColumnModel().getColumn(2).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblCTPhieu.getColumnModel().getColumn(3).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(0).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(2).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblCTPhieu_ChiTiet.getColumnModel().getColumn(3).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblHangHoaKho.getColumnModel().getColumn(0).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblHangHoaKho.getColumnModel().getColumn(2).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblPhieu.getColumnModel().getColumn(0).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());
        tblPhieu.getColumnModel().getColumn(1).setCellRenderer(TableNumberCellRenderer.getIntegerRenderer());

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblPhieu.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblPhieu.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tblPhieu.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }

    private void createQRCode() {
        int rowPhieuModel = tblPhieu.convertRowIndexToModel(rowPhieu);
        if (rowPhieuModel < 0) {
            MsgBox.alert(this, "Chưa chọn chi tiết phiếu!");
        } else {
            int maPhieu = (int) this.modelPhieu.getValueAt(rowPhieuModel, 6);
            try {
                BufferedImage bi = QRCode.generateQRCodeImage(String.valueOf(maPhieu));
                lblQRCodeImage.setIcon(new ImageIcon(bi));
                QRCodeDialog.setVisible(true);
            } catch (WriterException ex) {
                MsgBox.alert(this, "Lỗi tạo mã QR không thành công!");
                ex.printStackTrace();
            }
        }
    }

    // Xuất file excel
    private final String reportPath = "/com/stoman/reports/InPhieuKiemKho.jrxml";

    private void exportReportExcel() {
        int rowPhieuModel = tblPhieu.convertRowIndexToModel(rowPhieu);
        if (rowPhieuModel < 0) {
            MsgBox.alert(this, "Chưa chọn phiếu!");
            return;
        }

        try {
            int maKK = (int) this.modelPhieu.getValueAt(rowPhieuModel, 6);

            // Truyền tham số vào báo cáo
            HashMap parameters = new HashMap();
            parameters.put("MAKK", maKK);

            String fileName = "PhieuKiemKhoSo" + maKK;
            XReport.exportFile(fileName, reportPath, parameters);
        } catch (SQLException | JRException | IOException e) {
            MsgBox.alert(this, "Xuất file thất bại!");
            e.printStackTrace();
        }
    }

    // In báo báo
    private void printReport() {
        int rowPhieuModel = tblPhieu.convertRowIndexToModel(rowPhieu);
        if (rowPhieuModel < 0) {
            MsgBox.alert(this, "Chưa chọn phiếu!");
            return;
        }

        try {
            int maKK = (int) this.modelPhieu.getValueAt(rowPhieuModel, 6);

            // Truyền tham số vào báo cáo
            HashMap parameters = new HashMap();
            parameters.put("MAKK", maKK);

            String fileName = "PhieuKiemKhoSo" + maKK;
            XReport.printReport(fileName, reportPath, parameters);
        } catch (SQLException | JRException e) {
            MsgBox.alert(this, "In phiếu thất bại!");
            e.printStackTrace();
        }
    }

    // Cập nhật giao diện form theo hoạt động của người dùng
    private void updateStatus() {
        // Kiểm tra trạng thái chọn phiếu trên bảng
        boolean edit = (this.rowPhieu >= 0);
        boolean first = (this.rowPhieu == 0);
        boolean last = (this.rowPhieu == tblPhieu.getRowCount() - 1);

        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnXuatMaPhieu.setEnabled(edit);
        btnInPhieu.setEnabled(edit);
        btnXuatFile.setEnabled(edit);
        btnChiTiet.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

        // Kiểm tra vai trò người dùng, hạn chế quyền thủ kho
        boolean isManager = Auth.isManager();
        btnXoa.setVisible(isManager);

        // Cập nhật trạng thái update phiếu
        cboKho.setEnabled(!isUpdate);
    }

    private boolean isValidated() {
        if (txtNgayKiem.getDate() == null) {
            MsgBox.alert(this, "Chưa nhập ngày thực hiện!");
            txtNgayKiem.requestFocus();
            return false;
        }

        Date ngayLap = XDate.toDate(txtNgayLap.getText(), dateFormat);
        if (txtNgayKiem.getDate().before(ngayLap)) {
            MsgBox.alert(this, "Ngày kiểm kho không nhỏ hơn ngày lập phiếu!");
            txtNgayKiem.requestFocus();
            return false;
        }
        return true;
    }

    private void edit() {
        if (this.rowPhieu < 0) {
            return;
        }
        
        delCTP.clear();

        int rowPhieuModel = tblPhieu.convertRowIndexToModel(this.rowPhieu);
        int maPkk = (Integer) this.modelPhieu.getValueAt(rowPhieuModel, 6);
        PhieuKiemKho pkk = pkkDAO.selectByID(maPkk);
        this.setFormPhieu(pkk);
        tabs.setSelectedIndex(0);

        isUpdate = true;
        this.updateStatus();
        tblPhieu.setRowSelectionInterval(rowPhieu, rowPhieu);
    }

    // Hiển thị phiếu đầu danh sách
    private void first() {
        this.rowPhieu = 0;
        this.edit();
    }

    // Hiển thị phiếu kế trước
    private void prev() {
        if (this.rowPhieu > 0) {
            this.rowPhieu--;
            this.edit();
        }
    }

    // Hiển thị phiếu kế tiếp
    private void next() {
        if (this.rowPhieu < (tblPhieu.getRowCount() - 1)) {
            this.rowPhieu++;
            this.edit();
        }
    }

    // Hiển thị phiếu cuối danh sách
    private void last() {
        this.rowPhieu = tblPhieu.getRowCount() - 1;
        this.edit();
    }

    // Đổ lại dữ liệu 
    public void refreshForm() {

        this.fillToComboBoxKho();
        this.fillToTablePhieu();
        this.fillToTableCTPhieu();
        this.fillToTableHHkho();

        this.timer.restart();
    }

    // sau hai phút tải lại dữ liệu
    private Timer timer = new Timer(120000, (e) -> {
        refreshForm();
    });

    // Đổ tên bảng vào combobox tìm kiếm
    private void fillToComboBoxTimKiemCT() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTimKiemCT.getModel();
        model.removeAllElements();
        for (int i = 0; i < tblCTPhieu.getColumnCount(); i++) {
            String columnName = tblCTPhieu.getColumnName(i);
            model.addElement(columnName);
        }
    }

    // Lọc bảng theo từ khoá phiếu
    private void searchCTPhieu() {
        int columnFilter = cboTimKiemCT.getSelectedIndex();
        String keyword = txtTimKiemCT.getText();
        if (keyword.equals(defaultSearchHangHoa)) {
            keyword = "";
        }

        RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter(keyword.toLowerCase(), columnFilter);
        } catch (Exception e) {
            return;
        }
        sorterCTPhieu.setRowFilter(rf);
    }

    private void searchCTPhieu_ChiTiet() {
        String keyword = txtTimKiemCTP.getText();
        if (keyword.equals(defaultSearchHangHoa)) {
            keyword = "";
        }

        RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter(keyword.toLowerCase());
        } catch (Exception e) {
            return;
        }
        sorterCTPhieu_ChiTiet.setRowFilter(rf);
    }

    private void searchHangHoaKho() {
        String keyword = txtTimKiemHHKho.getText();
        if (keyword.equals(defaultSearchHangHoa)) {
            keyword = "";
        }

        RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter(keyword.toLowerCase());
        } catch (Exception e) {
            return;
        }
        sorterHHKho.setRowFilter(rf);
    }

    // Đổ tên bảng vào combobox tìm kiếm
    private void fillToComboBoxTimKiemPhieu() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTimKiemPhieu.getModel();
        model.removeAllElements();
        for (int i = 0; i < tblPhieu.getColumnCount(); i++) {
            String columnName = tblPhieu.getColumnName(i);
            if (tblPhieu.getColumnName(i).equalsIgnoreCase("HOÀN THÀNH")) {
                continue;
            }
            model.addElement(columnName);
        }
    }
//
    // Lọc bảng theo từ khoá phiếu

    private void searchPhieu() {
        int columnFilter = cboTimKiemPhieu.getSelectedIndex();
        if (columnFilter > 2) {
            columnFilter++;
        }
        String keyword = txtTimKiemPhieu.getText();
        if (keyword.equals(defaultSearchPhieu)) {
            keyword = "";
        }

        RowFilter<TableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter(keyword.toLowerCase(), columnFilter);
        } catch (Exception e) {
            return;
        }
        sorterPhieu.setRowFilter(rf);
    }

    // Ánh xạ dòng được chọn của bảng này sang bảng khác
    private void mapSelectionTable(JTable TableToClick, JTable TableToMap) {
        int rowTableToClick = TableToClick.convertRowIndexToModel(TableToClick.getSelectedRow());
        int rowTableToMap = TableToMap.convertRowIndexToView(rowTableToClick);
        TableToMap.setRowSelectionInterval(rowTableToMap, rowTableToMap);
    }
    
    // Nhấn enter không xuống dòng tiếp theo khi đang sửa ô trong table
    private void disableEnterCellNextLine(JTable table) {
        int row = table.getSelectedRow();
        if (row == 0) {
            row = table.getRowCount() - 1;
        } else {
            row--;
        }
        table.setRowSelectionInterval(row, row);
    }
    
}
