/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stoman.ui;

import com.stoman.dao.HangHoaDAO;
import com.stoman.dao.LoaiHangHoaDAO;
import com.stoman.entity.HangHoa;
import com.stoman.entity.LoaiHangHoa;
import com.stoman.utils.MsgBox;
import com.stoman.utils.XNumber;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MinhNH
 */
public class HangHoaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HangHoaJDialog
     */
    public HangHoaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        lblSapXepTheo = new javax.swing.JLabel();
        cboSapXepTheo = new javax.swing.JComboBox<>();
        pnlLoaiHangHoa = new javax.swing.JPanel();
        pnlLstLoaiHangHoa = new javax.swing.JScrollPane();
        lstLoaiHangHoa = new javax.swing.JList<>();
        btnThemList = new javax.swing.JButton();
        btnXoaList = new javax.swing.JButton();
        pnlThongTinHangHoa = new javax.swing.JPanel();
        lblMaHangHoa = new javax.swing.JLabel();
        txtMaHH = new javax.swing.JTextField();
        lblTenHangHoa = new javax.swing.JLabel();
        txtTenHH = new javax.swing.JTextField();
        lblDonViTinh = new javax.swing.JLabel();
        txtDonViTinh = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JFormattedTextField();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        pnlChuyen = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnlTblHangHoa = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StoMan - Quản lý hàng hoá");
        setAlwaysOnTop(true);

        lblTimKiem.setText("Tìm kiếm");

        lblSapXepTheo.setText("Sắp xếp theo");

        pnlLoaiHangHoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại hàng hoá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlLoaiHangHoa.setLayout(new java.awt.GridBagLayout());

        pnlLstLoaiHangHoa.setViewportView(lstLoaiHangHoa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.ipady = 108;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 1.0;
        pnlLoaiHangHoa.add(pnlLstLoaiHangHoa, gridBagConstraints);

        btnThemList.setText("Thêm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlLoaiHangHoa.add(btnThemList, gridBagConstraints);

        btnXoaList.setText("Xoá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlLoaiHangHoa.add(btnXoaList, gridBagConstraints);

        pnlThongTinHangHoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hàng hoá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        lblMaHangHoa.setText("Mã hàng hoá");

        lblTenHangHoa.setText("Tên hàng hoá");

        lblDonViTinh.setText("Đơn vị tính");

        lblDonGia.setText("Đơn giá");

        txtDonGia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout pnlThongTinHangHoaLayout = new javax.swing.GroupLayout(pnlThongTinHangHoa);
        pnlThongTinHangHoa.setLayout(pnlThongTinHangHoaLayout);
        pnlThongTinHangHoaLayout.setHorizontalGroup(
            pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenHangHoa)
                    .addComponent(lblMaHangHoa)
                    .addComponent(lblDonViTinh)
                    .addComponent(lblDonGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonViTinh)
                    .addComponent(txtMaHH)
                    .addComponent(txtTenHH)
                    .addComponent(txtDonGia))
                .addContainerGap())
        );
        pnlThongTinHangHoaLayout.setVerticalGroup(
            pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinHangHoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHangHoa)
                    .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHangHoa)
                    .addComponent(txtTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonViTinh)
                    .addComponent(txtDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonGia)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlChucNang.setLayout(new java.awt.GridLayout(0, 1));

        btnThem.setText("Thêm");
        pnlChucNang.add(btnThem);

        btnXoa.setText("Xoá");
        pnlChucNang.add(btnXoa);

        btnSua.setText("Sửa");
        pnlChucNang.add(btnSua);

        btnMoi.setText("Mới");
        pnlChucNang.add(btnMoi);

        pnlChuyen.setLayout(new java.awt.GridLayout(1, 0));

        btnFirst.setText("|<");
        pnlChuyen.add(btnFirst);

        btnPrev.setText("<<");
        pnlChuyen.add(btnPrev);

        btnNext.setText(">>");
        pnlChuyen.add(btnNext);

        btnLast.setText(">|");
        pnlChuyen.add(btnLast);

        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng hoá", "Tên hàng hoá", "Đơn vị tính", "Đơn giá"
            }
        ));
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        pnlTblHangHoa.setViewportView(tblHangHoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLoaiHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlThongTinHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSapXepTheo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboSapXepTheo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTblHangHoa))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongTinHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLoaiHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSapXepTheo)
                        .addComponent(cboSapXepTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        this.edit();
    }//GEN-LAST:event_tblHangHoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangHoaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangHoaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangHoaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangHoaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HangHoaJDialog dialog = new HangHoaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemList;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaList;
    private javax.swing.JComboBox<String> cboSapXepTheo;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblDonViTinh;
    private javax.swing.JLabel lblMaHangHoa;
    private javax.swing.JLabel lblSapXepTheo;
    private javax.swing.JLabel lblTenHangHoa;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JList<LoaiHangHoa> lstLoaiHangHoa;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlChuyen;
    private javax.swing.JPanel pnlLoaiHangHoa;
    private javax.swing.JScrollPane pnlLstLoaiHangHoa;
    private javax.swing.JScrollPane pnlTblHangHoa;
    private javax.swing.JPanel pnlThongTinHangHoa;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JFormattedTextField txtDonGia;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtTenHH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
    
    HangHoaDAO HHdao = new HangHoaDAO();
    LoaiHangHoaDAO LHHdao = new LoaiHangHoaDAO();
    
    String numPatern = "#,##0";
    private String header[] = {"MÃ HH", "TÊN HH", "ĐƠN GIÁ", "ĐVT"}; 
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    private DefaultListModel<LoaiHangHoa> lstModel = new DefaultListModel<LoaiHangHoa>();

    private void init() {
        this.setLocationRelativeTo(null);
        tblHangHoa.setModel(tblModel);
        lstLoaiHangHoa.setModel(lstModel);
        this.fillTable();
        this.fillList();
    }

    // Code phuong thức fillTable.
    private void fillTable() {
        tblModel.setRowCount(0);

        try {
            List<HangHoa> list = HHdao.selectAll();
            for (HangHoa hh : list) {
                Object[] row = {
                    hh.getMaHH(),
                    hh.getTenHH(),
                    XNumber.toString(hh.getDonGia(), numPatern),
                    hh.getDonViTinh()
                };
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    //Code phương  thức fillList.
    private void fillList() {
       lstLoaiHangHoa.removeAll();
       
       try {
            List<LoaiHangHoa> list = LHHdao.selectAll();
            for (LoaiHangHoa lhh : list) {
                
                lstModel.addElement(lhh);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    //Code phương thức getForm.
    private HangHoa getForm() {
        HangHoa hh = new HangHoa();
        hh.setMaHH(txtMaHH.getText());
        hh.setTenHH(txtTenHH.getText());
        hh.setDonViTinh(txtDonViTinh.getText());
        hh.setDonGia(XNumber.toDouble(txtDonGia.getText(), numPatern));
        hh.setMaLHH(lstLoaiHangHoa.getSelectedValue().getMaLHH());
        return hh;
    }

    //Code phương thức clearForm.
    private void clearForm() {
        this.setForm(new HangHoa());
        tblHangHoa.clearSelection();
        this.updateStatus();
    }
    
    //Code phương thức setForm.
    private void setForm(HangHoa hh) {
        txtMaHH.setText(hh.getMaHH());
        txtTenHH.setText(hh.getTenHH());
        txtDonViTinh.setText(hh.getDonViTinh());
        txtDonGia.setText(XNumber.toString(hh.getDonGia(), numPatern));
    }
    
    //Code phương thức updateStatus.
    void updateStatus() {
        
    }

    //Code phương thức insert
    private void insert() {
        HangHoa item = getForm();
        try {
            HHdao.insert(item);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công.");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại.");
        }
    }

    //Code phương thức Edit
    private void edit() {
        String maHH = (String) tblHangHoa.getValueAt(tblHangHoa.getSelectedRow(), 0);
         HangHoa hh = HHdao.selectByID(maHH);
         this.setForm(hh);
         this.updateStatus();
    }
}
