/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stoman.ui;

import com.stoman.dao.ChiTietPhieuDAO;
import com.stoman.dao.DoiTacDAO;
import com.stoman.dao.HangHoaDAO;
import com.stoman.dao.KhoDAO;
import com.stoman.dao.LoaiDoiTacDAO;
import com.stoman.dao.LoaiHangHoaDAO;
import com.stoman.dao.LuuTruDAO;
import com.stoman.dao.PhieuDAO;
import com.stoman.dao.ProcedureDAO;
import com.stoman.entity.ChiTietPhieu;
import com.stoman.entity.DoiTac;
import com.stoman.entity.HangHoa;
import com.stoman.entity.Kho;
import com.stoman.entity.LoaiDoiTac;
import com.stoman.entity.LoaiHangHoa;
import com.stoman.entity.Phieu;
import com.stoman.utils.Auth;
import com.stoman.utils.MsgBox;
import com.stoman.utils.SpinnerEditor;
import com.stoman.utils.XDate;
import com.stoman.utils.XNumber;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Huy
 */
public class PhieuNhapXuatKhoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form PhieuKiemKhoDialog
     */
    public PhieuNhapXuatKhoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChiTietPhieuDialog = new javax.swing.JDialog();
        pnlTblCTPhieu_main = new javax.swing.JScrollPane();
        tblCTPhieu_main = new javax.swing.JTable();
        pnlThongTinCTP = new javax.swing.JPanel();
        lblLoaiHH = new javax.swing.JLabel();
        lblTenHH = new javax.swing.JLabel();
        cboLoaiHH = new javax.swing.JComboBox<>();
        cboHangHoa = new javax.swing.JComboBox<>();
        pnlChucNangCTP = new javax.swing.JPanel();
        btnThemCTP = new javax.swing.JButton();
        btnXoaCTP = new javax.swing.JButton();
        btnGrpLoaiPhieu = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        pnlChiTiet = new javax.swing.JPanel();
        pnlTblCTPhieu_sub = new javax.swing.JScrollPane();
        tblCTPhieu_sub = new javax.swing.JTable();
        pnlThongTinPhieu = new javax.swing.JPanel();
        lblLoaiDT = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        lblNgayLap = new javax.swing.JLabel();
        lblNgayHoanThanh = new javax.swing.JLabel();
        lblDoiTac = new javax.swing.JLabel();
        lblNgayThucHien = new javax.swing.JLabel();
        lblLoaiPhieu = new javax.swing.JLabel();
        cboLoaiDT = new javax.swing.JComboBox<>();
        chkHoanThanh = new javax.swing.JCheckBox();
        rdoPhieuNhap = new javax.swing.JRadioButton();
        rdoPhieuXuat = new javax.swing.JRadioButton();
        txtNgayLap = new javax.swing.JFormattedTextField();
        txtNgayThucHien = new javax.swing.JFormattedTextField();
        txtNgayHoanThanh = new javax.swing.JFormattedTextField();
        txtMaNV = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        pnlGhiChu = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        cboDoiTac = new javax.swing.JComboBox<>();
        lblNgayHoanThanh1 = new javax.swing.JLabel();
        cboKho = new javax.swing.JComboBox<>();
        pnlNutDieuHuong = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnlChucNang1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        pnlDanhSach = new javax.swing.JPanel();
        scrollPane2 = new javax.swing.JScrollPane();
        tblPhieu = new javax.swing.JTable();

        tblCTPhieu_main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTPhieu_main.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCTPhieu_main.getTableHeader().setReorderingAllowed(false);
        pnlTblCTPhieu_main.setViewportView(tblCTPhieu_main);

        pnlThongTinCTP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu kiểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlThongTinCTP.setToolTipText("StoMan - Chi tiết phiếu kiểm kho");

        lblLoaiHH.setText("Loại hàng hoá");

        lblTenHH.setText("Tên hàng hoá");

        cboLoaiHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiHHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinCTPLayout = new javax.swing.GroupLayout(pnlThongTinCTP);
        pnlThongTinCTP.setLayout(pnlThongTinCTPLayout);
        pnlThongTinCTPLayout.setHorizontalGroup(
            pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinCTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenHH)
                    .addComponent(lblLoaiHH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboLoaiHH, 0, 338, Short.MAX_VALUE)
                    .addComponent(cboHangHoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlThongTinCTPLayout.setVerticalGroup(
            pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinCTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiHH)
                    .addComponent(cboLoaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinCTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenHH)
                    .addComponent(cboHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlChucNangCTP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlChucNangCTP.setLayout(new java.awt.GridLayout(0, 1));

        btnThemCTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/add.png"))); // NOI18N
        btnThemCTP.setText("Thêm");
        btnThemCTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTPActionPerformed(evt);
            }
        });
        pnlChucNangCTP.add(btnThemCTP);

        btnXoaCTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/cancel.png"))); // NOI18N
        btnXoaCTP.setText("Xoá");
        btnXoaCTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTPActionPerformed(evt);
            }
        });
        pnlChucNangCTP.add(btnXoaCTP);

        javax.swing.GroupLayout ChiTietPhieuDialogLayout = new javax.swing.GroupLayout(ChiTietPhieuDialog.getContentPane());
        ChiTietPhieuDialog.getContentPane().setLayout(ChiTietPhieuDialogLayout);
        ChiTietPhieuDialogLayout.setHorizontalGroup(
            ChiTietPhieuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChiTietPhieuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChiTietPhieuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChiTietPhieuDialogLayout.createSequentialGroup()
                        .addComponent(pnlThongTinCTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChucNangCTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTblCTPhieu_main, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap())
        );
        ChiTietPhieuDialogLayout.setVerticalGroup(
            ChiTietPhieuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChiTietPhieuDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChiTietPhieuDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongTinCTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChucNangCTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblCTPhieu_main, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StoMan - Quản lý phiếu nhập xuất kho");

        pnlTblCTPhieu_sub.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        tblCTPhieu_sub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTPhieu_sub.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCTPhieu_sub.getTableHeader().setReorderingAllowed(false);
        pnlTblCTPhieu_sub.setViewportView(tblCTPhieu_sub);

        pnlThongTinPhieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        lblLoaiDT.setText("Loại đối tác");

        lblMaNV.setText("Người lập");

        lblTrangThai.setText("Trạng thái");

        lblNgayLap.setText("Ngày lập");

        lblNgayHoanThanh.setText("Ngày hoàn thành");

        lblDoiTac.setText("Đối tác");

        lblNgayThucHien.setText("Ngày thực hiện");

        lblLoaiPhieu.setText("Loại phiếu");

        cboLoaiDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiDTActionPerformed(evt);
            }
        });

        chkHoanThanh.setText("Hoàn thành");

        btnGrpLoaiPhieu.add(rdoPhieuNhap);
        rdoPhieuNhap.setSelected(true);
        rdoPhieuNhap.setText("Phiếu nhập");

        btnGrpLoaiPhieu.add(rdoPhieuXuat);
        rdoPhieuXuat.setText("Phiếu xuất");

        txtNgayLap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtNgayLap.setEnabled(false);

        txtNgayThucHien.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));

        txtNgayHoanThanh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));

        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setLineWrap(true);
        txtGhiChu.setRows(5);
        txtGhiChu.setWrapStyleWord(true);
        pnlGhiChu.setViewportView(txtGhiChu);

        lblNgayHoanThanh1.setText("Kho");

        javax.swing.GroupLayout pnlThongTinPhieuLayout = new javax.swing.GroupLayout(pnlThongTinPhieu);
        pnlThongTinPhieu.setLayout(pnlThongTinPhieuLayout);
        pnlThongTinPhieuLayout.setHorizontalGroup(
            pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                            .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLoaiDT)
                                .addComponent(lblMaNV))
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThongTinPhieuLayout.createSequentialGroup()
                            .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNgayThucHien, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLoaiPhieu, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                        .addComponent(lblTrangThai)
                        .addGap(34, 34, 34)))
                .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLoaiDT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                                .addComponent(rdoPhieuNhap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoPhieuXuat)))
                        .addGap(24, 24, 24)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDoiTac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNgayHoanThanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(lblNgayHoanThanh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayHoanThanh)
                            .addComponent(cboKho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                                .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboDoiTac, 0, 196, Short.MAX_VALUE)
                                    .addComponent(txtNgayLap))
                                .addGap(18, 18, 18)
                                .addComponent(lblGhiChu))))
                    .addComponent(chkHoanThanh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThongTinPhieuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboLoaiDT, txtMaNV, txtNgayHoanThanh, txtNgayThucHien});

        pnlThongTinPhieuLayout.setVerticalGroup(
            pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhieuLayout.createSequentialGroup()
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoaiDT)
                            .addComponent(cboLoaiDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDoiTac)
                            .addComponent(lblGhiChu)
                            .addComponent(cboDoiTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNV)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayLap))
                        .addGap(12, 12, 12)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayThucHien)
                            .addComponent(txtNgayThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayHoanThanh)
                            .addComponent(txtNgayHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoaiPhieu)
                            .addComponent(rdoPhieuNhap)
                            .addComponent(rdoPhieuXuat)
                            .addComponent(lblNgayHoanThanh1)
                            .addComponent(cboKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThongTinPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrangThai)
                            .addComponent(chkHoanThanh))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlGhiChu))
                .addContainerGap())
        );

        pnlNutDieuHuong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điều hướng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlNutDieuHuong.setLayout(new java.awt.GridLayout(1, 0));

        btnFirst.setText("|<");
        pnlNutDieuHuong.add(btnFirst);

        btnPrev.setText("<<");
        pnlNutDieuHuong.add(btnPrev);

        btnNext.setText(">>");
        pnlNutDieuHuong.add(btnNext);

        btnLast.setText(">|");
        pnlNutDieuHuong.add(btnLast);

        pnlChucNang1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        pnlChucNang1.setLayout(new java.awt.GridLayout(5, 1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/add-32.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlChucNang1.add(btnThem);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/cancel-32.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlChucNang1.add(btnXoa);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/edit-property-32.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlChucNang1.add(btnSua);

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/new-document-32.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlChucNang1.add(btnMoi);

        btnChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/stoman/icons/more-details-32.png"))); // NOI18N
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pnlChucNang1.add(btnChiTiet);

        javax.swing.GroupLayout pnlChiTietLayout = new javax.swing.GroupLayout(pnlChiTiet);
        pnlChiTiet.setLayout(pnlChiTietLayout);
        pnlChiTietLayout.setHorizontalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlThongTinPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                        .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTblCTPhieu_sub)
                            .addGroup(pnlChiTietLayout.createSequentialGroup()
                                .addComponent(pnlNutDieuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChucNang1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlChiTietLayout.setVerticalGroup(
            pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChiTietLayout.createSequentialGroup()
                        .addComponent(pnlTblCTPhieu_sub, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlNutDieuHuong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlChucNang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlThongTinPhieu.getAccessibleContext().setAccessibleName("Thông tin phiếu nhập xuất\n kho");

        tabs.addTab("Thông tin phiếu nhập xuất", pnlChiTiet);

        tblPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhieu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPhieu.getTableHeader().setReorderingAllowed(false);
        tblPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuMouseClicked(evt);
            }
        });
        scrollPane2.setViewportView(tblPhieu);

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Danh sách phiếu nhập xuất", pnlDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiDTActionPerformed
        // TODO add your handling code here:
        fillToComboBoxDoiTac();
    }//GEN-LAST:event_cboLoaiDTActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        ChiTietPhieuDialog.setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void tblPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()<2) return;
        delCTP.clear();
        int row = tblPhieu.getSelectedRow();
        Phieu phieu = (Phieu) this.modelPhieu.getValueAt(row, 8);

        this.setFormPhieu(phieu);
        this.tabs.setSelectedIndex(0);
    }//GEN-LAST:event_tblPhieuMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemCTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTPActionPerformed
        this.insertCT();
    }//GEN-LAST:event_btnThemCTPActionPerformed

    private void cboLoaiHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiHHActionPerformed
        this.fillToComboBoxHangHoa();
    }//GEN-LAST:event_cboLoaiHHActionPerformed

    private void btnXoaCTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTPActionPerformed
        this.deleteCT();
    }//GEN-LAST:event_btnXoaCTPActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insertPhieu();
        this.clearForm();
        this.fillToTablePhieu();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.deletePhieu();
        this.clearForm();
        this.fillToTablePhieu();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.updatePhieu();
        this.clearForm();
        this.fillToTablePhieu();
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapXuatKhoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapXuatKhoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapXuatKhoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapXuatKhoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PhieuNhapXuatKhoJDialog dialog = new PhieuNhapXuatKhoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ChiTietPhieuDialog;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnFirst;
    private javax.swing.ButtonGroup btnGrpLoaiPhieu;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemCTP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaCTP;
    private javax.swing.JComboBox<String> cboDoiTac;
    private javax.swing.JComboBox<String> cboHangHoa;
    private javax.swing.JComboBox<String> cboKho;
    private javax.swing.JComboBox<String> cboLoaiDT;
    private javax.swing.JComboBox<String> cboLoaiHH;
    private javax.swing.JCheckBox chkHoanThanh;
    private javax.swing.JLabel lblDoiTac;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblLoaiDT;
    private javax.swing.JLabel lblLoaiHH;
    private javax.swing.JLabel lblLoaiPhieu;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayHoanThanh;
    private javax.swing.JLabel lblNgayHoanThanh1;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblNgayThucHien;
    private javax.swing.JLabel lblTenHH;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JPanel pnlChucNang1;
    private javax.swing.JPanel pnlChucNangCTP;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JScrollPane pnlGhiChu;
    private javax.swing.JPanel pnlNutDieuHuong;
    private javax.swing.JScrollPane pnlTblCTPhieu_main;
    private javax.swing.JScrollPane pnlTblCTPhieu_sub;
    private javax.swing.JPanel pnlThongTinCTP;
    private javax.swing.JPanel pnlThongTinPhieu;
    private javax.swing.JRadioButton rdoPhieuNhap;
    private javax.swing.JRadioButton rdoPhieuXuat;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblCTPhieu_main;
    private javax.swing.JTable tblCTPhieu_sub;
    private javax.swing.JTable tblPhieu;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JFormattedTextField txtNgayHoanThanh;
    private javax.swing.JFormattedTextField txtNgayLap;
    private javax.swing.JFormattedTextField txtNgayThucHien;
    // End of variables declaration//GEN-END:variables

    private PhieuDAO pDAO = new PhieuDAO();
    private ChiTietPhieuDAO ctpDAO = new ChiTietPhieuDAO();
    private LoaiDoiTacDAO ldtDAO = new LoaiDoiTacDAO();
    private DoiTacDAO dtDAO = new DoiTacDAO();
    private LuuTruDAO ltDAO = new LuuTruDAO();
    private LoaiHangHoaDAO lhhDAO = new LoaiHangHoaDAO();
    private HangHoaDAO hhDAO = new HangHoaDAO();
    private KhoDAO kDAO = new KhoDAO();
    private ProcedureDAO spDAO = new ProcedureDAO();
    
    private DefaultTableModel modelPhieu;
    private DefaultTableModel modelCTPhieu;
    
    private String numFormat = "#,##0.0";
    private String dateFormat = "dd-MM-yyyy";
    
    private boolean isUpdate = false;

    void init() {
        this.setLocationRelativeTo(null);
        
        ChiTietPhieuDialog.pack();
        ChiTietPhieuDialog.setLocationRelativeTo(null);
        ChiTietPhieuDialog.setModalityType(ModalityType.APPLICATION_MODAL);
        ChiTietPhieuDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        
        // Dữ liệu hàng tiêu đề bảng
        String headerPhieu[] = {"Mã phiếu", "Đối tác" , "Loại", "Kho" , "Trạng thái",
            "Ngày thực hiện", "Ngày hoàn thành", "Ngày lập", "Người lập"};
        this.modelPhieu = new DefaultTableModel(headerPhieu, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

            @Override
            public Class getColumnClass(int columnIndex) {
                if (getValueAt(0, columnIndex) == null) {
                    return Object.class;
                }
                return getValueAt(0, columnIndex).getClass();
            }
        };
        String headerCTPhieu[] = {"STT", "Tên hàng hóa", "Số lượng", "Đơn giá", "Phieu"};
        this.modelCTPhieu = new DefaultTableModel(headerCTPhieu, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 2 || column == 3) return true;
                return false;
            }

            @Override
            public Class getColumnClass(int columnIndex) {
                return Integer.class;
            }
        };

        this.fillToTablePhieu();
        this.fillToComboBoxLoaiDT();
        this.fillToComboBoxLoaiHH();
        this.fillToComboBoxKho();
        
        tblPhieu.setModel(modelPhieu);
        tblCTPhieu_sub.setModel(modelCTPhieu);
        tblCTPhieu_main.setModel(modelCTPhieu);
        
        this.formatTable();
        
        this.clearForm();
    }

    // Đổ dữ liệu phiếu nhập xuất
    void fillToTablePhieu() {
        modelPhieu.setRowCount(0);
        List<Phieu> list = pDAO.selectAll();
        int i = 1;
        for (Phieu p : list) {
            int maLT = ctpDAO.getOnlyOneMaLT(p.getMaPhieu());
            if(maLT == 0) continue;
            int maKho = ltDAO.getMaKho(maLT);
            Kho kho = kDAO.selectByID(maKho);
            modelPhieu.addRow(new Object[]{
                i++,
                dtDAO.getTenDT(p.getMaDT()),
                p.isLoai() ? "Nhập" : "Xuất",
                kho,
                p.isTrangThai() ? "Đã hoàn thành" : "Chưa hoàn thành",
                XDate.toString(p.getNgThucHien(), dateFormat),
                XDate.toString(p.getNgHoanThanh(), dateFormat),
                XDate.toString(p.getNgayLap(), dateFormat + " (hh:MM:ss)"),
                p
            });
        }
    }

    // Đổ dữ liệu chi tiết phiếu
    void fillToTableCTPhieu() {
        modelCTPhieu.setRowCount(0);
        try {
            String maPhieu = tblCTPhieu_sub.getToolTipText();
            if(maPhieu == null) return;
            List<ChiTietPhieu> list = ctpDAO.selectByMaPhieu(Integer.parseInt(maPhieu));
            if(list.size()<1) return;
            int i = 1;
            for (ChiTietPhieu ctp : list) {
                String maHH = ltDAO.selectByID(ctp.getMaLT()).getMaHH();
                HangHoa hh = hhDAO.selectByID(maHH);
                modelCTPhieu.addRow(new Object[]{
                    i++,
                    hh,
                    XNumber.toString(ctp.getSoLuong(), numFormat),
                    XNumber.toString(ctp.getDonGia(), numFormat),
                    ctp.getMaCTP()
                });
            }
            tblCTPhieu_sub.setModel(modelCTPhieu);
            tblCTPhieu_main.setModel(modelCTPhieu);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Đổ dữ liệu ComboBox loại đối tác
    void fillToComboBoxLoaiDT() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            List<LoaiDoiTac> list = ldtDAO.selectAll();
            for(LoaiDoiTac ldt : list) {
                model.addElement(ldt);
            }
            cboLoaiDT.setModel(model);
            fillToComboBoxDoiTac();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Đổ dữ liệu ComboBox đối tác
    void fillToComboBoxDoiTac() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            LoaiDoiTac ldt = (LoaiDoiTac) cboLoaiDT.getSelectedItem();
            List<DoiTac> list = dtDAO.selectByLoaiDT(ldt.getMaLDT());
            for(DoiTac dt : list) {
                model.addElement(dt);
            }
            cboDoiTac.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Đổ dữ liệu vào ComboBox kho
    void fillToComboBoxKho() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            List<Kho> list = kDAO.selectAll();
            for(Kho k : list) {
                model.addElement(k);
            }
            cboKho.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Đổ dữ liệu ComboBox loại hàng hoá
    void fillToComboBoxLoaiHH() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            List<LoaiHangHoa> list = lhhDAO.selectAll();
            for(LoaiHangHoa lhh : list) {
                model.addElement(lhh);
            }
            cboLoaiHH.setModel(model);
            fillToComboBoxHangHoa();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Đổ dữ liệu ComboBox hàng hoá
    void fillToComboBoxHangHoa() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        try {
            LoaiHangHoa lhh = (LoaiHangHoa) cboLoaiHH.getSelectedItem();
            List<HangHoa> list = hhDAO.selectByLoaiHangHoa(lhh.getMaLHH());
            for(HangHoa hh : list) {
                model.addElement(hh);
            }
            cboHangHoa.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Lấy dữ liệu từ form phiếu nhập
    private Phieu getFormPhieu() {
        LoaiDoiTac ldt = (LoaiDoiTac) cboLoaiDT.getSelectedItem();
        Phieu p = new Phieu();
        p.setLoai(rdoPhieuNhap.isSelected());
        p.setMaDT(ldt.getMaLDT());
        p.setMaNV(txtMaNV.getText());
        p.setNgHoanThanh(XDate.toDate(txtNgayHoanThanh.getText(), dateFormat));
        p.setNgThucHien(XDate.toDate(txtNgayThucHien.getText(), dateFormat));
        p.setNgayLap(XDate.toDate(txtNgayLap.getText(), dateFormat + "(hh:MM:ss)"));
        p.setTrangThai(chkHoanThanh.isSelected());
        p.setGhiChu(txtGhiChu.getText());
        return p;
    }
    
    // Nhập dữ liệu vào form phiếu nhập
    private void setFormPhieu(Phieu p) {  
        DoiTac dt = dtDAO.selectByID(p.getMaDT());
        LoaiDoiTac ldt = ldtDAO.selectByID(dt.getMaLDT());
        Kho kho = (Kho) tblPhieu.getValueAt(tblPhieu.getSelectedRow(), 3);
        cboLoaiDT.setSelectedItem(ldt);
        cboDoiTac.setSelectedItem(dt);
        txtMaNV.setText(p.getMaNV());
        txtNgayLap.setText(XDate.toString(p.getNgayLap(), dateFormat + "(hh:MM:ss)"));
        txtNgayThucHien.setText(XDate.toString(p.getNgThucHien(), dateFormat));
        txtNgayHoanThanh.setText(XDate.toString(p.getNgHoanThanh(), dateFormat));
        cboKho.setSelectedItem(kho);
        if(p.isLoai()) rdoPhieuNhap.setSelected(true);
        else rdoPhieuXuat.setSelected(true);
        chkHoanThanh.setSelected(p.isTrangThai());
        txtGhiChu.setText(p.getGhiChu());
        tblCTPhieu_sub.setToolTipText(p.getMaPhieu().toString());
        
        this.fillToTableCTPhieu();
    }
    
    // Lấy dữ liệu từ form chi tiết phiếu
    private ChiTietPhieu getFormCTPhieu(int row) {
        ChiTietPhieu ctp = new ChiTietPhieu();
        ctp.setSoLuong(XNumber.toDouble((String) modelCTPhieu.getValueAt(row, 2), numFormat));
        ctp.setDonGia(XNumber.toDouble((String) modelCTPhieu.getValueAt(row, 3), numFormat));
        Integer maCTP = (Integer) modelCTPhieu.getValueAt(row, 4);
        ctp.setMaCTP(maCTP);

        return ctp;
    }
    
    // Thêm hàng hóa vào bảng Chi tiết
    private void insertCT(){
        if(isUpdate){
            return;
        }
        else {
            modelCTPhieu.addRow(new Object[]{
                tblCTPhieu_main.getRowCount()+1,
                (HangHoa) cboHangHoa.getSelectedItem(),
                XNumber.toString(0.0, numFormat),
                XNumber.toString(0.0, numFormat),
                0
            });            
        }
    }
    
    // Xóa hàng hóa khỏi chi tiết
    private ArrayList<ChiTietPhieu> delCTP = new ArrayList<>();
    
    private void deleteCT(){
        int delRow = tblCTPhieu_main.getSelectedRow();
        if(isUpdate){
            delCTP.add((ChiTietPhieu)modelCTPhieu.getValueAt(delRow, 4));
        }
        modelCTPhieu.removeRow(delRow);
        for (int i = 0; i < modelCTPhieu.getRowCount(); i++) {
            modelCTPhieu.setValueAt(i+1, i, 0);
        }
    }
    
    // Nhập phiếu mới vào hệ thống và cập nhật thông tin hàng hóa
    private void insertPhieu(){
        Phieu phieu = this.getFormPhieu();
        ChiTietPhieu ctp;
        pDAO.insert(phieu);
        
        int maPhieu = pDAO.getMaPhieuByNVandCreatedDate(phieu.getMaNV(), phieu.getNgayLap());
        
        int rows = modelCTPhieu.getRowCount();
        
        if(phieu.isLoai()){
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                HangHoa hh = (HangHoa) modelCTPhieu.getValueAt(i, 1);
                Kho kho = (Kho) cboKho.getSelectedItem();
                
                spDAO.insertNhap(ctp, maPhieu, hh, kho);
            }
        }  
        else{
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                HangHoa hh = (HangHoa) modelCTPhieu.getValueAt(i, 1);
                Kho kho = (Kho) cboKho.getSelectedItem();
                
                spDAO.insertXuat(ctp, maPhieu, hh, kho);
            }
        }
        MsgBox.alert(this, "Thêm phiếu " + (phieu.isLoai()?"nhập":"xuất") + " thành công!");
    }
    
    // Cập nhật phiếu vào hệ thống và cập nhật thông tin hàng hóa
    private void updatePhieu(){
        Phieu phieu = this.getFormPhieu();
        String maPhieu = tblCTPhieu_sub.getToolTipText();
        
        if(maPhieu == null) return;
        phieu.setMaPhieu(Integer.valueOf(maPhieu));
        Kho kho = (Kho) cboKho.getSelectedItem();
        pDAO.update(phieu);
        
        ChiTietPhieu ctp;
        int rows = modelCTPhieu.getRowCount();
        if(phieu.isLoai()){
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                
                if(ctp.getMaCTP()!=0)
                    spDAO.updateNhap(ctp);
                else{
                    HangHoa hh = (HangHoa) modelCTPhieu.getValueAt(i, 1);
                    spDAO.insertNhap(ctp, phieu.getMaPhieu(), hh, kho);
                }
            }
            for (ChiTietPhieu ctpDel : delCTP) {
                spDAO.deleteNhap(ctpDel);
            }
        }  
        else{
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                
                if(ctp.getMaCTP()!=0)
                    spDAO.updateXuat(ctp);
                else{
                    HangHoa hh = (HangHoa) modelCTPhieu.getValueAt(i, 1);
                    spDAO.insertXuat(ctp, phieu.getMaPhieu(), hh, kho);
                }
            }
            for (ChiTietPhieu ctpDel : delCTP) {
                spDAO.deleteXuat(ctpDel);
            }
        }
        MsgBox.alert(this, "Cập nhật phiếu " + (phieu.isLoai()?"nhập":"xuất") + " thành công!");
    }
    
    // Xoa phieu khoi he thong
    private void deletePhieu(){
        Phieu phieu = this.getFormPhieu();
        String maPhieu = tblCTPhieu_sub.getToolTipText();
        
        if(maPhieu == null) return;
        
        int rows = modelCTPhieu.getRowCount();
        ChiTietPhieu ctp;
        if(phieu.isLoai()){
            for (ChiTietPhieu ctpDel : delCTP) {
                spDAO.deleteNhap(ctpDel);
            }
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                if(ctp.getMaCTP()!=0) spDAO.deleteNhap(ctp);
            }
        }else{
            for (ChiTietPhieu ctpDel : delCTP) {
                spDAO.deleteXuat(ctpDel);
            }
            for (int i = 0; i < rows; i++) {
                ctp = getFormCTPhieu(i);
                if(ctp.getMaCTP()!=0) spDAO.deleteXuat(ctp);
            }
        }
        
        pDAO.delete(Integer.valueOf(maPhieu));

        MsgBox.alert(this, "Xóa phiếu " + (phieu.isLoai()?"nhập":"xuất") + " thành công!");
    }
    
    // Xóa trắng form
    private void clearForm(){
        cboLoaiDT.setSelectedIndex(0);
        cboDoiTac.setSelectedIndex(0);
        txtMaNV.setText(null); //Auth.user.getMaNV()
        Date NgayLap = new Date(System.currentTimeMillis());
        txtNgayLap.setText(XDate.toString(NgayLap, dateFormat + "(hh:MM:ss)"));
        txtNgayThucHien.setText(null);
        txtNgayHoanThanh.setText(null);
        rdoPhieuNhap.setSelected(true);
        cboKho.setSelectedIndex(0);
        chkHoanThanh.setSelected(false);
        txtGhiChu.setText(null);
        tblCTPhieu_sub.setToolTipText(null);
        this.fillToTableCTPhieu();
        
        isUpdate = false;
    }

    // cập nhật giao diện form theo hoạt động
    private void updateStatus() {
//        boolean edit = (this.row >= 0);
//        boolean first = (this.row == 0);
//        boolean last = (this.row == tblNguoiHoc.getRowCount() - 1);
//        
//        // trạng thái form
//        btnThem.setEnabled(!edit);
//        btnSua.setEnabled(edit);
//        btnXoa.setEnabled(edit && Auth.isManager());
//        btnMoi.setEnabled(edit);
//
//        // trạng thái điều hướng
//        btnFirst.setEnabled(!first);
//        btnLast.setEnabled(!last);
    }
    
    private void formatTable(){
        tblPhieu.setAutoCreateRowSorter(true);
        tblCTPhieu_sub.setAutoCreateRowSorter(true);
        tblCTPhieu_main.setAutoCreateRowSorter(true);
        
        //giấu cột maCTP
        TableColumnModel tcm = tblCTPhieu_sub.getColumnModel();
        tcm.removeColumn(tcm.getColumn(4));
        tcm = tblCTPhieu_main.getColumnModel();
        tcm.removeColumn(tcm.getColumn(4));

        // Chỉnh độ rộng hàng trong bảng
        tblCTPhieu_sub.setRowHeight(25);
        tblCTPhieu_main.setRowHeight(25);
        tblPhieu.setRowHeight(25);
        
        // Thêm chức năng nhập cho bảng
        tblCTPhieu_main.getColumnModel().getColumn(2).setCellEditor(new SpinnerEditor(0.0, 0.0, 1000000000.0, 1000.0));
        tblCTPhieu_main.getColumnModel().getColumn(3).setCellEditor(new SpinnerEditor(0.0, 0.0, 1000000000.0, 1000.0));
        tblCTPhieu_sub.getColumnModel().getColumn(2).setCellEditor(new SpinnerEditor(0.0, 0.0, 1000000000.0, 1000.0));
        tblCTPhieu_sub.getColumnModel().getColumn(3).setCellEditor(new SpinnerEditor(0.0, 0.0, 1000000000.0, 1000.0));
    }
}
